### ISSUE TITLE
Spectators can't see other Spectator messages in Spectator Chat

### ISSUE THREAD

**Issue by botcscriptcheck** [ThePandemoniumInstitute/botc-release#100]
**Describe the bug**
In a game with more than one spectator, only the ST can see messages sent by the Spectators, and other Spectators can't see anything that anyone else has seen

**To Reproduce**
1. Join a game and do not take a seat
2. Have multiple players as Spectators who are not in seats
3. Try to talk to the other Spectators, and have them try to talk to you
4. No messages from other Spectators can be seen

**Expected behavior**
All Spectators to be able to see other messages from spectators

**Screenshots**
![Player View](https://github.com/ThePandemoniumInstitute/botc-release/assets/135992257/d23591c7-0cfa-4d9e-a309-28d92ce073d1)
![Storyteller View](https://github.com/ThePandemoniumInstitute/botc-release/assets/135992257/850f6ae7-53c8-4eea-baeb-6569dd77743b)

**Standalone app (please complete the following information):**
 - OS: Windows 11
 - Version: 3.15.3

**Additional context**
- Game session name: #seq
- Date and time when it happened: 11pm 18 Sept 2023 NZST

**Comment by bra1n** [comment]
Thanks, this will be fixed with the next update. :-)
