### ISSUE TITLE
Accept chat requests with keyboard (accessibility issue)

### ISSUE THREAD

**Issue by CRSnyder** [ThePandemoniumInstitute/botc-release#101]
**Is your feature request related to a problem? Please describe.**

Currently it seems the only way to accept a chat request is by clicking on an icon to join on the left side of the page.  There's a few issues I have with this, having dexterity challenges:

- The icon is very small, so it takes extra time to get my mouse over it.
- The icon is off to the side, and my mouse is typically more centralized
- The position of the icon on the screen seems to change as requests come in or disappear.
- Time is of the essence during chat time, so making joining a chat quicker would be very appreciated.

**Describe the solution you'd like**
I'd love there to be a keyboard shortcut to accept chat request. If there are multiple requests, perhaps the shortcut could show a list on requests and then typing a number would accept the particular request.

**Describe alternatives you've considered**
If a keyboard shortcut isn't possible, can the icon be enlarged and maybe centralized?

**Comment by botcscriptcheck** [comment]
To my knowledge you can also accept chat requests by clicking the players name on the sidebar when they send a request or by sending them a request when you have one from them, which will auto-join you.

**Comment by bra1n** [comment]
It took a while, but with the next update, you'll get 3 shortcuts to accept either of the first 3 incoming chat requests. You can rebind them, by default they are "1", "2" and "3".
