### ISSUE TITLE
Keyboard shortcuts to choose responses to storyteller's night inquiries

### ISSUE THREAD

**Issue by CRSnyder** [ThePandemoniumInstitute/botc-release#102]
Keyboard shortcuts for choosing responses to the storytellers question/information would be helpful (especially if the shortcuts were also visible on the dialog).  Again, time is the essence in this game, so anything to speed up responses from people who are slower with the mouse is useful.

Also, I think I clicked off the dialog one time by mistake and the dialog disappeared.  I wasn't able to get it back and the ST wound up calling me.  It would be nice if important dialogs couldn't be dismissed so easily.

**Comment by bra1n** [comment]
You can re-open the night signal window by clicking on the top right "Night info" text that shows up when you've received some information from the ST.
As for the shortcuts: I guess it makes sense to have them as a player, but for the ST there are probably too many buttons to assign them to shortcuts. I could match the shortcuts to the player version, but the extra buttons from the ST view would probably have to be without shortcuts...

**Comment by CRSnyder** [comment]
Thanks for the info about reopening the night signal window.  I missed that.  May I request a shortcut key for that, or highlighting the text somehow if the window is dismissed?  This is probably scope creep, but just wanted to put that out there.

**Comment by bra1n** [comment]
Sure, I'll add a shortcut for showing / hiding the night info as a player, with the next update. (defaults to "N", same as switching to night phase as ST)
