### ISSUE TITLE
Option to automatically sound the gong after timer ended.

### ISSUE THREAD

**Issue by GarethOates** [ThePandemoniumInstitute/botc-release#105]
**Is your feature request related to a problem? Please describe.**
Option to automatically sound the "gong" when the timer is up.

**Describe the solution you'd like**
Love the new timer feature.  I was hoping it would be possible to have it automatically sound the gong when it's time to come back to the townsquare.  When I'm following people around in rooms etc it can be difficult to see that the timer has ended, behind the cameras etc.

**Describe alternatives you've considered**
I've just been minimising the cameras and seeing that the timer has ended, and then sounding the gong manually.  It would be nice to have this happen automatically.

**Additional context**
Nope.

**Comment by bra1n** [comment]
Added with v3.18.0
