### ISSUE TITLE
Don't Immediately Remove Night Info At Day Start

### ISSUE THREAD

**Issue by botcscriptcheck** [ThePandemoniumInstitute/botc-release#106]
**Is your feature request related to a problem? Please describe.**
Occasionally as a Player I'll be writing down my night information and suddenly it becomes day time and my info disappears, or as a Storyteller while I'm waiting for a player to respond to a card I've sent, I might accidentally make it day time, wiping the card from them and not getting a response.

**Describe the solution you'd like**
Have Night Info cards not disappear until the same timer that determines a "day" has passed. I noticed a few weeks ago that if you take it from night then to day and then quickly back to night, it will keep the correct night order number, and I think the night info should stay available for that same duration to prevent mishaps like this

**Describe alternatives you've considered**
Just trying to remember pings or being VERY careful to not touch the night phase button when I don't need to.

**Additional context**

**Comment by bra1n** [comment]
Yeah that's not a bad idea, I'll add it to the list. :)

**Comment by bra1n** [comment]
Added with v3.18.0
