### ISSUE TITLE
Add Minions and Imp to First Night Sheet for Trouble Brewing

### ISSUE THREAD

**Issue by Smutchings** [ThePandemoniumInstitute/botc-release#108]
**Is your feature request related to a problem? Please describe.**
Currently, the First Night sheet for Trouble Brewing does not show or mark the steps where you would tell the Minions who their demon is and tell the Demon who their minions are.

**Describe the solution you'd like**
Add these steps to the First Night sheet with an automatic marker, as is done with other abilities/steps in the Night Phase.

**Additional context**
This is particularly useful for starter Storytellers.

**Comment by bra1n** [comment]
Hey Sam,
I'm not sure I understand what you're asking for. The First Night sheet for TB (or any other script, for that matter), do show and mark the Demon Info / Minion Info steps:
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/325521/cd1b48db-f39f-4c94-a2aa-2fe6328cef00)
Am I missing something?

**Comment by Smutchings** [comment]
Apologies. This "issue" occurred because there were fewer than 7 seats in the game. My mistake.
