### ISSUE TITLE
Unable to show the Bluff interface for Demons

### ISSUE THREAD

**Issue by Smutchings** [ThePandemoniumInstitute/botc-release#109]
**Describe the bug**
Currently unable to find a way to show the Bluffs interface for the demon, so Bluffs are not stored/shown in the app interface for the Story Teller, Demon or for their minions to manually ad..

**To Reproduce**
Missing Interface, so can't be "reproduced"

**Expected behavior**
I would expect there to be a keyboard shortcut or on-screen command for showing and setting up the Bluffs for the Demon.

**Comment by bra1n** [comment]
Hey Sam,
both the ST and the Demon player will automatically have a bluffs tab on the left side in the app:
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/325521/333074a1-8c00-49c3-8499-8f10b59e8c02)
Did your test game maybe have less than 7 players? In that case, you're playing a Teensyville game where there are no bluffs for the Demon.

**Comment by Smutchings** [comment]
Apologies. This "issue" occurred because there were fewer than 7 seats in the game. My mistake.
