### ISSUE TITLE
Sound Control: Master Volume

### ISSUE THREAD

**Issue by JammingzNZ** [ThePandemoniumInstitute/botc-release#113]
**Is your feature request related to a problem? Please describe.**
Being able to Control the master Volume of the Web App would be great. When playing other sounds from the same browser, volume control to be able raise/lower the overall volume of the app would be handy so you can easily balance between other Web Apps.

**Describe the solution you'd like**
Slider similar to that for each individual player Volume but adjusts the Gain/Loss of everything/Everyone. 

**Describe alternatives you've considered**
Alternative solution would adjust the Slider of each individual to the level set. I would reccommend not doing this, as if someone is very loud/quiet you'd have to then individually adjust them.

Also you may consider that you want to have a master volume, a master player volume and a master sound effect volume slider. 

**Additional context**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/14990579/defd313d-7c34-42b5-b180-0c268cee1a11)

**Comment by bra1n** [comment]
Yup, that makes sense and would also replace the global sound mute toggle with a slider for better control of the volume.

**Comment by bra1n** [comment]
Alright, this will be in the next update!
