### ISSUE TITLE
Shortcut key to toggle Mark

### ISSUE THREAD

**Issue by GarethOates** [ThePandemoniumInstitute/botc-release#115]
**Is your feature request related to a problem? Please describe.**
The process of removing the on the block mark from a player is a bit cumbersome at the moment.  It would be nice to have a shortcut key to be able to toggle this, without having to nominate a player, double-click mark and then end it.

**Describe the solution you'd like**
A shortcut key that can remove the mark on a player.

**Describe alternatives you've considered**
Maybe something like "M" if it's not already in use.

**Additional context**
Thanks for all you do! :)

**Comment by bra1n** [comment]
Alright, the "cast vote" (default: Space) shortcut will now also work for the ST to toggle an execution mark, with the next app update.
