### ISSUE TITLE
Weird tokens during nominations

### ISSUE THREAD

**Issue by MollofPower** [ThePandemoniumInstitute/botc-release#116]
**Described**
The bug rotates the player circles towards the middle when they have characters with the "team": "token".

**To Reproduce**
1. Load a json with this text:

``[{"id": "_meta",
    "name": "",
    "author": ""
  },
{"id": "test",
    "edition": "custom",
    "name": "Test",
    "team": "token",
    "ability": "Not important."
  }]``

2. Change someones character to "Test"
3. Start a nomination

**Expected behavior**
For the token to be rotated towards the middle.
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/159932372/03b034d2-114a-40bb-986b-855992400378)

**Browser app (please complete the following information):**
 - OS: Windows
 - Browser: google chrome
 - Version: 120.0.6099.225

**Additional context**
- Game session name: #62948
- Browser console log: 
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/159932372/0cd29633-8073-4dc6-b530-adaea20c14c1)
- Date and time when it happened: repeatedly, reproduced 13 of february 2024, 17.05 GMT+1

**Comment by bra1n** [comment]
Alright, it looks like you're trying to load a script with an unsupported "team" name. Using "token" there is not supported, but I'll add some safeguards against stuff like this in the future.

**Comment by bra1n** [comment]
Will be fixed in 3.21.3
