### ISSUE TITLE
Game Session information is clickable even when you are unable to change them

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#117]
**Describe the bug**
With the latest release, if you click on WiFi symbol you are given information about the Game Session. Some of these items are selectable, and even expand e.g. Chat Server but you can't click them or change the settings even though they highlight as selectable.

**Expected behavior**
Configuration that is not changeable by the user should not display as selectable.

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/82e04853-b8c2-494d-adf1-a25c1a35d282)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/a9b79bdf-2b8c-4641-82f9-b5a199b468e5)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/1eb44705-5868-48e0-b35e-a5380be1e18c)

**Browser app (please complete the following information):**
 - Google Chrome: Version 121.0.6167.161 (Official Build) (64-bit)
 -

**Comment by bra1n** [comment]
Thanks, this will be fixed in 3.21.3
