### ISSUE TITLE
ST reminder token hover UI hard to access

### ISSUE THREAD

**Issue by Clijmart** [ThePandemoniumInstitute/botc-release#118]
**Describe the bug**
Reminder tokens placed on the Storyteller are hard to edit. Probably due to the hover UI element being hidden behind the ST token.
Especially troublesome for editing custom reminder tokens.

**Expected behavior**
The UI element for editing the reminder token should probably stay active when trying to hover over the edit/rotate option.

**Screenshots/Videos**
https://github.com/ThePandemoniumInstitute/botc-release/assets/21392642/b0eb6e8a-b75f-4a8b-8ab9-0cb1314e6642

**Browser app (please complete the following information):**
 - Opera One (version: 106.0.4998.70)
 - BOTC Online v3.21.3

**Comment by bra1n** [comment]
Thanks, I can confirm this bug and it will be fixed with 3.21.4!
