### ISSUE TITLE
Game result staying hidden when playing with animations off

### ISSUE THREAD

**Issue by Clijmart** [ThePandemoniumInstitute/botc-release#119]
**Describe the bug**
When playing with 'Show Animations' toggled off, the game result is never shown.

**Expected behavior**
When playing with animations turned off, the game result should probably just appear.

**Screenshots**
Player Perspective:
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/21392642/7d6999c6-e823-4ac8-acdc-6f401d335948)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/21392642/8c9a4ec1-fd4e-4931-ae7a-5b2760f874f3)

ST Perspective:
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/21392642/3703daaa-0969-47b5-89c9-b1116ab4f4a8)

**Browser app (please complete the following information):**
- Opera One (version: 106.0.4998.70)
- BOTC Online v3.21.3

**Comment by bra1n** [comment]
Thanks for the report, there was indeed a small typo that prevented it from showing up when animations are disabled. This will be fixed in 3.21.4!
