### ISSUE TITLE
Camera not working in Firefox (Windows 11)

### ISSUE THREAD

**Issue by Velcorn** [ThePandemoniumInstitute/botc-release#120]
**Describe the bug**
My webcam (Logitech C920 Pro HD) won't turn on in Firefox on Windows 11. It simply remains black and the light doesn't come on. Works fine in Edge.

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/8927053/f8a42093-2595-494a-b3e0-8f950f405b3d)

**Browser app (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 122.0.1

**Comment by bra1n** [comment]
Can you try using the app in an incognito Firefox window without any extensions enabled? Firefox is rather peculiar when it comes to accessing cam and microphone - it needs them to be not in use on any other software. Do you maybe have other apps running (OBS, Discord, other browsers) that might be accessing the cam? In that case, try closing all other programs and then try using it on Firefox.
Also, what do you see when you run the Cam / Mic setup on the Chat settings menu?
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/325521/e781fd8e-46c7-4e1b-ba74-bf8ecb4995e8)

**Comment by Velcorn** [comment]
Thanks for the response, sorry for getting back so late. I just updated my graphics drivers AND uninstalled OBS and it works now. So whoever has the same problems and finds this issue, try those two things first ^^
