### ISSUE TITLE
Leaving lobby during grim reveal

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#124]
**Describe the bug**
After leaving a lobby as a spectator with grim access during the grim reveal I was stuck in grim reveal mode in another lobby too, even after leaving and joining again and also after taking a seat by clicking on all available seats.

**Standalone app (please complete the following information):**
 - Version 3.21.3

![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/f84b9582-b903-4f7d-bf3f-41b1af1e32b2)

**Comment by bra1n** [comment]
Hi @Unbaloav, thanks for the report! This is a known issue and will be fixed with 3.21.4
