### ISSUE TITLE
Private message "letters" stay on screen.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#127]
**Describe the bug**
The letters between 2 players stay on screen if you have deactivated animations.

![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/9a145a48-5d4e-4185-a154-ebc41652126f)

**Standalone app (please complete the following information):**
 - Version 3.21.4

**Comment by bra1n** [comment]
Thanks, this will be fixed in the next update!
