### ISSUE TITLE
When clicking on the corner of an alive players character a wierd window opens.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#129]
**Describe the bug**
When clicking on the corner of an alive players character (you have to have a character assigned to them) during the night a window opens saying "The Storyteller woke you:".

**To Reproduce**
1. sit down as a player
2. assign a token to another player
3. go to the night
4. click on the outmost side of the other players character
5. see the following window open

**Screenshots**
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/d389c9a1-6d85-4ac1-8485-aa5223d26fb4)

**Expected behavior**
It shouldn't open at all.

**Standalone app (please complete the following information):**
 - Version 3.21.4

**Comment by bra1n** [comment]
Thanks, I can confirm this is a bug and will fix it for the next update!
