### ISSUE TITLE
Keyboard Shortcuts are still active when entering a custom game name for a new game

### ISSUE THREAD

**Issue by Smutchings** [ThePandemoniumInstitute/botc-release#132]
**Describe the bug**
When entering a custom name for a new game, if you use one of the letters that the app uses for Lobby shortcuts, then the dialogue box closes for creating the game and the shortcut is activated.

**To Reproduce**
1. Go to 'https://online.bloodontheclocktower.com/play'
2. Click on 'Create Game'
3. Enter a custom game which uses one of the letters used for a shortcut - such as C 
4. See error - Dialogue closes and shortcut is invoked.

**Expected behavior**
When you are typing a new name for a created game, the shortcuts for the lobby should be deactivated.

**Browser app (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 122.0.6261.69 (Official Build) (x86_64)

**Additional context**
- Game session name: WhiteCliffs
- Date and time when it happened: 01/03/2024 19:00-19:10

**Comment by bra1n** [comment]
Hey Sam, thanks for the report, this has already been fixed in the web app and will be fixed in the standalone app soon as well. :)

**Comment by Smutchings** [comment]
Just gone to create a new game in V3.22.0 and typing L into the game name box appears to still trigger the keyboard shortcut to start Local Play

**Comment by Smutchings** [comment]
Full cache reset from the Privacy menu resolved the issue.
