### ISSUE TITLE
Malfunctioning error on changing voting time too fast

### ISSUE THREAD

**Issue by TrulyTHRiO** [ThePandemoniumInstitute/botc-release#134]
**Bug description:**
When changing _certain_ settings too fast (particularly the Storyteller: Vote Time setting, since you cannot enter a value and need to click +/- multiple times), an error message is shown:
"An error happened
Your app seems to be malfunctioning, please clear your browser cache."

**Steps to reproduce:**
Log in to online.bloodontheclocktower.com
Create/join a game
Increment/decrement the Storyteller: Vote Time setting quickly

**Result:**
"An error happened
Your app seems to be malfunctioning, please clear your browser cache."

**Video:**
https://github.com/ThePandemoniumInstitute/botc-release/assets/55783018/d29271d6-1c89-46ac-88ee-7ad4a6b2bfc3

**Expected behaviour:**
I would imagine the message to the server that the setting has been changed would wait until the settings menu has been closed or the changes have been manually applied. (This is what happens with the Name border setting for example, the changes are only made once the settings menu is closed which means it does not have the same issue.)

**Browser app:**
Replicated on:
Browser: Vivaldi Browser
Version: 6.6.3271.48 (Stable channel) (64-bit)
Browser: Microsoft Edge
Version: 122.0.2365.66 (Official build) (64-bit)

**Comment by bra1n** [comment]
Thanks, this isn't really a bug but a design flaw and I'll turn it into a range slider with the next update, to prevent this kind of issue. :-)
