### ISSUE TITLE
Can no longer bind CTRL to shortcuts 

### ISSUE THREAD

**Issue by zarst** [ThePandemoniumInstitute/botc-release#135]
**Describe the bug**
Up until recently I have bound Control to my options for Muting Microphone.
Today it appears that no longer works, I've tried other keys including shift and it works as intended. I tried binding CTRL to other settings (leave a conversation) and it also failed to work. 
I assumed it was a Keyboard malfunction but CTRL ALT DELETE still functions so keyboard is registering the CTRL key.
I have tried binding either key and it replciates the issue.
I have asked another user to repeat my steps and they have gotten the same results.

**To Reproduce**
1. Go to App Setting-> Shortcuts
2. Click on any Shortcut and press CTRL or Control
3. Attemtp to perform shorcut.

**Expected behavior**
When assigning a Shorcut to CTRL expected action is that it fuctions correctly.

**Screenshots**
N/A

**Browser app (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version Version 122.0.6261.112 (Official Build) (64-bit)

**Standalone app (please complete the following information):**
 - Version [e.g. 3.2.1]

**Additional context**
- Game session name: community
- Browser console log: [shortcut Shift + CTRL + J or Option + ⌘ + J]
- Date and time when it happened: 12/03/24 ~6:30pm EST

My username is zarst and email zarst@hotmail.com

**Comment by bra1n** [comment]
Thanks, this has been fixed with 3.22.2! :)
