### ISSUE TITLE
Vote bug.

### ISSUE THREAD

**Issue by Edynol123** [ThePandemoniumInstitute/botc-release#136]
**Describe the bug**
Sometimes when someone lowers their hand at the last second, it still counts their vote.

**To Reproduce**

**Expected behavior**
A vote to not count when a players lowers their hand.

**Screenshots**
Try to include a screenshot of the browser console as well, if you're using the browser version. (Windows/Linux: Shift + CTRL + J, Mac: Option + ⌘ + J or Option + ⌘ + C)

**Browser app (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version [e.g. 3.2.1]

**Standalone app (please complete the following information):**
 - Version [e.g. 3.2.1]

**Additional context**
- Game session name: reds
- Browser console log: [shortcut Shift + CTRL + J or Option + ⌘ + J]
- Date and time when it happened: March 13 2024

**Comment by bra1n** [comment]
Hi @Edynol123,
what you describe is something that can happen in every game with an online service. If your connection to the game server is slower than your reaction speed, you will end up missing the point in time where you can do something (like voting) at the last moment. There isn't really anything I could do here easily, as code that "predicts" events like the vote clock hand is pretty complicated for very little gain. So my suggestion would be to not vote at the very last second, but ideally half a second earlier than that. ;-)
