### ISSUE TITLE
Script as secondary window

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#137]
**Is your feature request related to a problem? Please describe.**
I really like to have the script on my secondary monitor because opening it in the app moves part of the townsquare behind my voice and text chat windows. Currently I always have to save the JSON, and then upload it to 
https://script.bloodontheclocktower.com/ save it as PDF and then open that.

**Describe the solution you'd like**
It would be great to have a button next to "Save JSON" that creates a pop-up window with the script to move to another screen.

**Comment by bra1n** [comment]
Yeah, this has been requested before. Unfortunately, it is not something that can be done easily, since the app (currently) only supports one active tab at the same time. I'll think about it. :-)

**Comment by bra1n** [comment]
This is live now, at least for Chrome / Edge browser and the Windows standalone app!
