### ISSUE TITLE
Grim access icons on players (just a visual bug)

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#139]
**Describe the bug**
After starting a new game (with a new script) the players that previously were spectators with grim access still had the grim access icon next to their names. Was fixed by reloading.

**To Reproduce**
I don't know how to reproduce it.

**Screenshots**
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/40758f3f-fd8d-47aa-a950-d0e09118fb37)

**Standalone app (please complete the following information):**
 - Version 3.22.2

**Comment by bra1n** [comment]
I can't seem to reproduce this one? Starting a new game without finishing (as in: revealing the Grimoire) the old game will not remove Grimoire access. If you do finish a game and reveal the Grimoire, then that's the point where the grim access is removed and the user list is updated accordingly.

**Comment by bra1n** [comment]
Closed due to inactivity.
