### ISSUE TITLE
Kazali & Summoner jinx doesn't appear on character list

### ISSUE THREAD

**Issue by BobTheBigBox** [ThePandemoniumInstitute/botc-release#140]
**Describe the bug**
When creating a script containing a Kazali and a Summoner, the character list does not list Kazali & Summoner as one of the Jinxes

**To Reproduce**
1. On the script creation tool https://script.bloodontheclocktower.com/ put Summoner and Kazali on the script
2. Click the "Save" button and choose "To clipboard"
3. In the blood on the clocktower official tool (found on browser version), open settings
4. Click on Select Edition [2]
5. Click "Custom Script" and choose the option "Paste"
6. Open the character list

**Expected behavior**
The Kazali & Summoner jinx appears in the category "Jinxed"

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/164490787/e0318030-0eb6-44ae-a5c9-b044dabe5cd3)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/164490787/f75ccc35-ab1c-4aab-99f7-7180f86f71bc)

**Browser app (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome 122 on Windows 10, BOTC Online v3.23.0

**Standalone app (please complete the following information):**
Not tested

**Additional context**
- Game session name: 28252

**Comment by bra1n** [comment]
Hey Bob, thanks for the report. This was an oversight and has been fixed now. :-)
