### ISSUE TITLE
Player Was Dropped Mult

### ISSUE THREAD

**Issue by sabenite** [ThePandemoniumInstitute/botc-release#143]
**Describe the bug**
a player was disconnected from the game repeatedly

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/465496/72291665-419f-4548-8711-0ce1cc31b9d4)

**Browser app (please complete the following information):**
 - OS: Mac OSX
 - Browser FireFox
 - Version 3.23.1
- Game session name: maemae
- Date and time when it happened: [3/25/23 8-10pm est]

**Comment by bra1n** [comment]
Hi @sabenite, thanks for the report! Am I correct in assuming that the user who had the disconnects was Yumi? If so, it seems like they had internet connection issues, frequently losing the connection to the game server. The console log doesn't show any app related errors (the messages there are all browser extension related), so my assumption would be that their internet wasn't stable enough to reliably stay connected to the app.
Unfortunately there isn't anything I can do about this on the server side. My suggestion would be to use a cable connection to the internet or maybe a place with better WiFi.
