### ISSUE TITLE
Close Lobbies with only spectators

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#145]
Lately there have often been lobbies where just a spectator with TF/Minion tier is in and all other players and the ST are disconnected.
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/25408b82-ef2d-4115-9fab-34b36f9c4ed1)
I think it would be good if these lobbies would close after some time.

**Comment by bra1n** [comment]
I don't know - would you suggest the same for lobbies that have 2 spectators but nobody else in them? What if those spectators are currently chatting with each other? I guess I could eventually auto-close them, but currently they're not really harming anyone. I guess it would make sense for the Storyteller to be removed eventually, if they've been offline for more than X minutes, just so people can (re-)use the game session and become the Storyteller.

**Comment by Unbaloav** [comment]
Usually it is only 1 spectator and they are (usually) only still there because they are AFK.
And at least for me it is a bit annoying having to click on these lobbies to see if they are really dead or if the ST is just offline for a short time, especially when most lobbies (4/6 right now) are this way.
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/b722d099-ce04-4f58-97e3-c2f8896dc772)

**Comment by bra1n** [comment]
Alright, starting with the next update you will no longer see public games in the lobby that only have spectators in them.
