### ISSUE TITLE
Incorrect domain on https://github.com/ThePandemoniumInstitute

### ISSUE THREAD

**Issue by genestealer** [ThePandemoniumInstitute/botc-release#146]
Please note, you have listed here: https://github.com/ThePandemoniumInstitute
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/5207490/4c98d746-82c4-49b9-8864-77b6b09383b5)
`storyteller@bloodclocktower.com`
However the domain is not active and bounces emails.
The correct domain seems to be
`storyteller@bloodontheclocktower.com`

**Comment by bra1n** [comment]
Oh dang, apologies for the wrong email address there! Fixed it now. :)

**Comment by genestealer** [comment]
Awesome, wow you have added loads of new URLs and tags 😊
