### ISSUE TITLE
Roles stay on a user after they switch lobby and you follow their role doesn't clear

### ISSUE THREAD

**Issue by robinswood-botc** [ThePandemoniumInstitute/botc-release#147]
**Describe the bug**
Seen after playing a game with player A in seat 10 marked them as poisoner. Game ended player A moved server. Roughly 5 mins later I go spectate that new server that was already in night 1. Player A was again in seat 10 and already marked up as poisoner. All other tokens were blank (apart from a traveler)

**To Reproduce**
Haven't been able to reproduce as don't have a buddy to hand to test. Below is my best guess at reproducing it.
1. Go to server A with Player Z in seat 2 and sit down in seat 3
2. Click on their token and change it to poisoner
3. Get Player Z to move to server B and have them sit in seat 2
4. Wait till that server is in night 1
5. Enter as a spectator.
6. See Seat 2 is already marked

**Expected behavior**
Entering a new server should have a clear grim

**Screenshots**
The bellow screenshot is a mock up of the bug done on a different server
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/165334218/27b1f8e4-4f83-4db7-803f-5adbd926ae5b)

**Browser app (please complete the following information):**
 - OS: Windows 11
 - Browser Edge 
 - Version 123.0.2420.65 
- BOTC version 3.23.1

**Additional context**
- Game session name: [e.g. #12345]
- Browser console log: [shortcut Shift + CTRL + J or Option + ⌘ + J]
- Date and time when it happened: 28-03-2024  Around 21:30 gmt

**Comment by bra1n** [comment]
Yeah, the app remembers which role you assigned to other players if they are in the same seat and the current session doesn't have a traveler or a different player there. I'll see if I can fix that.

**Comment by bra1n** [comment]
This will be fixed with the next update.
