### ISSUE TITLE
Game ending does not clear open grimoire requests

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#149]
**Describe the bug**
I am unable to "Request Grimoire Access" even though I am a spectator and other people are able to request grim Access.

It's unclear precisely what the flow was to get into this position but I'll lay that out.

I joined a game as a spectator that had just ended and I requested Grimoire Access. I was not given access to the Grimoire.
A new game was started in the same session, a player was promoted to ST and the original ST changed to a player.
I have been unable to Request Grimoire Access for the new game.

**Expected behavior**
I am allowed to Request Grimoire Access

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/d6a5db6e-6a3a-440e-8c9d-0a3e2e0272b5)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/d9cdd91b-2475-4cf9-b2c1-1c1020f56a61)

**Browser app (please complete the following information):**
 - Chrome
 - Version 123.0.6312.88 (Official Build) (64-bit)

**Additional context**
- Game session name: #3513
- 5th April 2024, 00:13 UTC+1

**Comment by AdmiralGT** [comment]
Refreshing did unlock being able to request Grimoire Access

**Comment by bra1n** [comment]
Ah yes, it looks like the game ending did not clear your grimoire request. I'll fix that.

**Comment by bra1n** [comment]
Alright, I looked into it and there wasn't really a bug per se here, but the way the interface / backend handled it, made it rather obscure and easy to miss for (new) STs. This will be streamlined with the next update.
