### ISSUE TITLE
Traveller Token is not Cleared when selecting Clear Grimoire

### ISSUE THREAD

**Issue by QRS-Komplex** [ThePandemoniumInstitute/botc-release#152]
**Describe the bug**
Played with a Traveller today and the selection of Clear Grimoire didn´t erase the Traveller Token. All other Tokens were cleared.

**To Reproduce**
1. Click on "Clear Grimoire" in Menu
2. Traveller Token was still

**Expected behavior**
All Tokens would be cleared

**Browser app (please complete the following information):**
 - Firefox 124.0.2 

**Additional context**
- Game session name: [e.g. #22656]

**Comment by bra1n** [comment]
Hey @QRS-Komplex, were you a player in that game or the Storyteller? Only the Storyteller can remove (or add) travellers.

**Comment by QRS-Komplex** [comment]
Ahh sure. Sorry! I was a player. Yeah makes sense that only the st can :)
