### ISSUE TITLE
Night information changes when moving seats during the night

### ISSUE THREAD

**Issue by TomH099** [ThePandemoniumInstitute/botc-release#153]
If a traveller is added/moved part way through the night, night information will refer to the seat instead of the player, this can mean that if a storyteller checks the night info, it can show the wrong players name for targeted abilities 

**To Reproduce**
1. At night add a traveller
2. Start running night phase using cards
3. Move traveller to desired seat
4. See error in night info

**Expected behavior**
Night info to show the correct player when travellers seats move

**Browser app (please complete the following information):**
 - Browser chrome
 - OS: Windows 10
 - Version 3.23.2

**Additional context**
- Game session name: 19786
- Date and time when it happened: 12/04/24 22:30

**Comment by bra1n** [comment]
Hey Tom, thanks for the bug report. This is a general issue, though: if you move seats at night, the night info won't be updated accordingly. I'll see if I can fix that. Thanks for the report!

**Comment by bra1n** [comment]
This will be fixed with the next update.
