### ISSUE TITLE
Camera keeps switching off

### ISSUE THREAD

**Issue by tomm-tommm** [ThePandemoniumInstitute/botc-release#154]
![Capture](https://github.com/ThePandemoniumInstitute/botc-release/assets/167125263/8b4fe51c-1e37-4f7f-bc25-1019d55d79ea)
**Describe the bug**
When I log on to the app, the camera starts enabled but then it switches itself off. It is still enabled in the top right corner of the screen, but the light on my webcam isn't on and my picture isn't showing

**To Reproduce**
-Log in to the app 
-The webcam permissions are enabled on Chrome and on the laptop. They are also enabled within the app
-The camera will initially show available but will then hide

**Expected behavior**
The camera should remain available

**Screenshots**
Try to include a screenshot of the browser console as well, if you're using the browser version. (Windows/Linux: Shift + CTRL + J, Mac: Option + ⌘ + J or Option + ⌘ + C)

**Browser app (please complete the following information):**
Chrome 123.0.6312.122

Multiple game sessions e.g 15/04 7pm GMT

**Comment by bra1n** [comment]
Hi Tom, can you please take a screenshot of the Settings -> Chat tab while in game and seated as a player/ST?
And can you run the cam / mic setup from the settings once and share a screenshot of that, too? Feel free to remove any identifying information first, of course.

**Comment by tomm-tommm** [comment]
I've also got a video I can share in private message of the issue happening

**Comment by bra1n** [comment]
Alright, it looks like your setup _should_ work! Would you mind DM'ing me on Discord so we can give it a try in the app? My Discord name is also @bra1n.

**Comment by bra1n** [comment]
Fixed by switching to the standalone app.
