### ISSUE TITLE
[FEATURE]: Option to toggle off new messages.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#157]
### What problem are you trying to solve?

The new messages "Player joined/left the game", "Player took/vacated seat x", "Player requested/received Grimoire access", "Player no longer has Grimoire access" and "Player used a Ghost Vote" tend to make the readability of Public chat really bad. (Personally I think the "Player has died" message is fine because it doesn't happen in such a high frequency.)

### Describe the solution you'd like

Probably the easiest solution would be an option to toggle it off.

### Alternatives you have considered

It would also be great in a seperate tab (in case you want it but not in between the normal messages), would be great to be able to toggle it off either way.

### Comments

![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/a25cb01c-ba7d-4d2a-8c33-9147f655c9e7)

**Comment by bra1n** [comment]
Thanks for the suggestion, I'm currently working on improving the chat interface, so this will be addressed with the next update.
