### ISSUE TITLE
[BUG]: Spectator chat remains open after sitting

### ISSUE THREAD

**Issue by inspirationfollows** [ThePandemoniumInstitute/botc-release#159]
### Description

I was in a session in spectator chat, with the chat window pulled open. I then sat down in a seat on the grim, but was able to continue chatting in spectator chat until I clicked to a different chat tab. 
<img width="1164" alt="Screenshot 2024-04-20 at 12 07 22 PM" src="https://github.com/ThePandemoniumInstitute/botc-release/assets/167640388/eb103a8c-5bf3-419e-8eb2-a264eb1e60f1">
In the screenshot, the final "Thanks braxx" message was sent in spectator chat to spectators after I had claimed my seat on the grim. Once I switched to a different text chat tab, I could no longer access the spectator chat.

### Steps to reproduce

1 Be a spectator between games, 
2 Type in spectator chat and leave spectator chat open
3 Sit down in an open seat while text window is still open and on spectator chat
4 Type message into chat window

### Browser

Chrome

### Operating System

Mac

### Date and Time

April 20th 12:15pm Central time

### Game Session

https://botc.app/join/swapswap

**Comment by bra1n** [comment]
Thanks, this will be fixed with the next update!
