### ISSUE TITLE
[BUG] New message counter does not reduce if channel is unchanged

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#160]
### Description

I'm a player in a game. The current "Public" chat notification number is at 4, because there have been 4 new messages since I opened the chat. However, the counter does not decrease when making any sort of interactions with the chat menu except for changing to a different channel or closing and re-opening the text box, at which point it clears them all.

Any interaction with the chat box (clicking into the area, writing a message, sending a message) should clear the current "new messages" notification number 

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/3476614/1df7919b-5e0f-4f3d-b899-cd1ae8cd9b13)

### Steps to reproduce

1. Enter game
2. Open Public text chat
3. Wait for public events to happen

### Browser

Chrome

### Operating System

Windows

### Date and Time

April 21st 2024, 15:10 UTC+1

### Game Session

sundayclonk

**Comment by bra1n** [comment]
Hey AdmiralGT, thanks for the report. This is a known bug which will be fixed with the next update. :-)
