### ISSUE TITLE
[BUG] New Chat: Spectators Unable To See Private Chats

### ISSUE THREAD

**Issue by CriticalTankard** [ThePandemoniumInstitute/botc-release#161]
### Description

I'm uncertain if this is a "Bug", so apologies if this is the incorrect place for it . As a spectator, you can no longer see private text messages between players (uncertain if storytellers can). 

### Steps to reproduce

1. Enter game
2. Remain as Spectator
3. Have other players in seats
4. Open Public text chat
5. Wait for player to private message eachother

### Browser

Chrome

### Operating System

Windows

### Date and Time

April 21, 2024 at 11:20 EST

**Comment by bra1n** [comment]
Hi @CriticalTankard, thanks for the bug report! I assume you mean when you have received Grimoire access, right? Because otherwise, normal spectators shouldn't see private messages at all. This particular bug will be fixed with the next update, as it has been reported already. :-)

**Comment by CriticalTankard** [comment]
Hi, yes. Apologies, this is once Grimoire access is received. Thanks!
