### ISSUE TITLE
[BUG] Unable to interact or see player tokens

### ISSUE THREAD

**Issue by RonennOtter** [ThePandemoniumInstitute/botc-release#162]
### Description

I was storytelling a game, stepped down, and afterward I was unable to change any player tokens as a ST or player. When I tried to interact with the player tokens, all I could do as a ST was change their death shrouds. As a player, nothing happened.  I logged into the lobby via the web version and everything worked as expected. 

This issue persisted after:
coming back to being ST
relogging
uninstalling/reinstalling the standalone app
creating a new lobby entirely

Oh yeah. I couldn't see the tokens either.  As player or ST.  I couldn't see my own token, and as a ST, I couldn't see anyone else's tokens either

### Steps to reproduce

As far as I'm aware, it was a sudden incident.  I was STing a game, we went to the Grim reveal, and afterwards everything stopped working as expected.

### Browser

Standalone app

### Operating System

Windows

### Date and Time

04/21/2024 at 11:15 EST

### Game Session

ottower

**Comment by bra1n** [comment]
Hi @RonennOtter, thanks for the bug report! Did you maybe switch to the town square side by accident? That would explain what you were describing - just press "T" to switch back. :)

**Comment by RonennOtter** [comment]
Oh yup, that'd do it.  Cheers
