### ISSUE TITLE
[FEATURE] automatic grim access

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#163]
### What problem are you trying to solve?

From my experience basically all STs that have Grimoire Access set to Yes give grim access to anyone that asks for it, which I assume can be a bit distracting from the game.

### Describe the solution you'd like

I think it would be usefull to not only have the Server option for Grimoire Access to be between Yes and No, but also something like Auto, which would meen that any spectator that asks for Grim Access automatically receives it without the ST having to grant it.

**Comment by bra1n** [comment]
Yeah, I agree that it would probably make sense to change the Grimoire Access tag to "Yes", "Ask" and "No", with "Ask" being the default. In case of "Yes" it would auto-approve the requests.

**Comment by VinylVault** [comment]
I like this, although I think `Auto` should be the default, as STing is already busy enough especially at night or pre-game, which in my experience is when most requests come in.  If STs want to limit then they will know (and be bothered) to change the setting

**Comment by bra1n** [comment]
I disagree, we have already had reports of players using a second account with Grimoire access to cheat and having Auto as the default would make that even easier.

**Comment by bra1n** [comment]
Hey everyone, this feature will be added to the app with the next update. There will then be 3 options for Grimoire Access: Ask (default), Yes (auto-approve) and No (auto-decline)!
