### ISSUE TITLE
[BUG] Text chat always shows a "1"

### ISSUE THREAD

**Issue by Arakasim** [ThePandemoniumInstitute/botc-release#165]
### Description

When closing the text chat in town it always displays with a 1 even when there is no new message there.

### Steps to reproduce

1. open chat and see all messages.
2. close chat
3. it will still display a 1 showing there is an unread message

### Browser

Chrome

### Operating System

Windows

### Date and Time

24/04/2024 00:57 GMT

### Game Session

troubletown

**Comment by bra1n** [comment]
Hey, can you take a screenshot of the text tab please, when this happens again? I suspect that the "1" on the tab means there is a new spectator / private message that you haven't read yet.

**Comment by bra1n** [comment]
closed due to inactivity
