### ISSUE TITLE
[BUG] timer persists from spectated game to new game

### ISSUE THREAD

**Issue by chrisshieh-direct** [ThePandemoniumInstitute/botc-release#166]
### Description

I was spectating a game, then decided to leave the game to go to the lobby. The game had a timer that was running when I left it. Then I created a private game, and when I did the previously running timer was still going.

### Steps to reproduce

1. Go to botc.app
2. Spectate a game, leave it while there is a timer running
3. From the lobby, create a new game
4. Timer is still running
![Screenshot 2024-04-24 at 12 45 21 AM](https://github.com/ThePandemoniumInstitute/botc-release/assets/112592422/db42442a-16ed-4ab0-a4e2-ad91d8d143f8)

### Browser

Chrome

### Operating System

Mac

### Date and Time

April 24, 12:30 AM Pacific Time

**Comment by bra1n** [comment]
Alright, this will be fixed with the next update.
