### ISSUE TITLE
[BUG] Website password resets fail since migration to botc.app

### ISSUE THREAD

**Issue by ryantheleach** [ThePandemoniumInstitute/botc-release#167]
### Description

After the transition to botc.app, I was unable to receive a password reset email.

My friend who attempted to reset their password on botc.app managed to receive the email, but it linked to checkout.bloodontheclocktower.com instead of to botc.app

After resetting the password, they were unable to login to the new domain.

### Browser

Chrome

### Operating System

Mac

### Date and Time

8:23PM 24/04/2024 Adelaide UTC+9:30

**Comment by bra1n** [comment]
Hey Ryan, the link to checkout.bloodontheclocktower.com is correct - your app account is also the same account that is being used on the shop. If you're unable to reset your passwort, please send us an email to support@botc.app with your account email address and I can either change the account email or try sending a reset link from our end.

**Comment by ryantheleach** [comment]
@bra1n I recommend testing that the password reset flow is working though, my friend was unable to log in after resetting even after getting the email.

**Comment by bra1n** [comment]
I've just tried it again once more and it worked flawlessly for me. On the app, I entered my email and a wrong password, then I clicked on the "Reset" link, waited for the reset email, clicked on the button in that email, entered a new password on the reset page, then went back to the app and logged in with the new password. It seems like you didn't actually end up changing the password?
