### ISSUE TITLE
[BUG] If a player is DC'd, and the lobby has 25 players in it, they can't get back in to retake their seat

### ISSUE THREAD

**Issue by chrisshieh-direct** [ThePandemoniumInstitute/botc-release#168]
### Description

I was in a 15-player game. One player DC'd. When they rebooted, they could not get back into the lobby because there were 25 players in the lobby, so they couldn't retake their seat. The ST had to kick a spectator so that the original player could get in to take their seat.

### Steps to reproduce

1. Have a game running, with 25 players in the lobby.
2. Disconnect a player.
3. Have them attempt to get back into the lobby when it has 25 players in it.

### Browser

Chrome

### Operating System

Mac

### Date and Time

April 24 4:18 AM Pacific

**Comment by bra1n** [comment]
Hi Chris, thank you for your bug report! In the situation that you describe, was the player already in their seat when they got disconnected? If so, they should have still been able to rejoin the game, as seated players (and Storytellers) do not count against the 25 user limit for a game session.
