### ISSUE TITLE
[BUG] TypeError on changing scripts (and more)

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#170]
### Description

When the ST changed the Script I got kicked with the following error message:
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/593560a1-5af5-4de7-9c43-4feee27c5e67)
I was the only player in the lobby and also able to rejoin, but even after restarting the app I was getting kicked when changing the Script. 
(It also happened when being promoted to ST. And when changing scripts as an ST)

edit: after exploring the other s.history Bug that I accidently encountered while reproducing this one, this error also happend when the ST got kicked and when they joined back in.
edit2: it also happened on grim reveal
edit3: it also happened on clearing the grim 

### Steps to reproduce

1. have a Lobby created
2. join that lobby
3. let the script be changed
4. encounter error

### Browser

Standalone app

### Operating System

Windows

### Date and Time

April 26th, 11AM GMT

### Game Session

38435

### Relevant console log output

```shell
Opening the console didn´t work in the App.
```

**Comment by bra1n** [comment]
Hey Unbaloav, thanks for the report, this should be fixed with 3.25.1 now. :-)
