### ISSUE TITLE
[BUG] s.history undefined error after being promoted to ST

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#171]
### Description

When being promoted to ST while being the ST earlier that session I was kicked with the following error:
![grafik](https://github.com/ThePandemoniumInstitute/botc-release/assets/161200654/e0680752-1f0e-476f-821e-a6efb77b35dd)

### Steps to reproduce

(0. be ST and stop being the ST)
1. be promoted to ST
2. accept it
3. encounter error

### Browser

Firefox

### Operating System

Windows

### Date and Time

April 26th, 12AM GMT

### Game Session

38435

### Relevant console log output

```shell
console log was empty
```

**Comment by bra1n** [comment]
Hey Unbaloav, thanks for the report, this should be fixed with 3.25.1 now. :-)
