### ISSUE TITLE
[FEATURE] Allow adding Jinxes to official characters in the app

### ISSUE THREAD

**Issue by AuroraKy** [ThePandemoniumInstitute/botc-release#173]
### What problem are you trying to solve?

Custom jinxes like courtier & summoner can't be made unless you recreate the courtier or summoner by making something like a courtier2/summoner2 since just writing a jinx in the json is ignored if the id is a pre-existing character.

### Describe the solution you'd like

```
{
    "id": "courtier",
    "jinxes": [
        {"id": "summoner", "reason": "The Courtier may not choose to make the Summoner drunk with their ability."}
    ]
  }
```
Adding this instead of {"id":"courtier"} should still add the courtier but also add the custom jinx.

### Alternatives you have considered

You can recreate the entire courtier like this to add it, which does not really seem that great of a solution
```
{
    "id": "courtier2",
    "name": "Courtier",
    "edition": "bmr",
    "image": [
        "https://botc.app/img/courtier_g.73bc8e54.webp",
        "https://botc.app/img/courtier_e.511ff974.webp"
    ],
    "team": "townsfolk",
    "firstNight": 19,
    "firstNightReminder": "The Courtier either shows a 'no' head signal, or points to a character on the sheet. If the Courtier used their ability: If that character is in play, that player is drunk.",
    "otherNight": 8,
    "otherNightReminder": "Reduce the remaining number of days the marked player is poisoned. If the Courtier has not yet used their ability: The Courtier either shows a 'no' head signal, or points to a character on the sheet. If the Courtier used their ability: If that character is in play, that player is drunk.",
    "reminders": ["Drunk 3",
        "Drunk 2",
        "Drunk 1",
        "No ability"],
    "setup": false,
    "ability": "Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.",
    "jinxes": [
        {"id": "summoner", "reason": "The Courtier may not choose to make the Summoner drunk with their ability."}
    ]
  }
```

### Comments

You could argue in this case that courtier and summoner should just not be on the same script but this is just an example. I think letting you change the standard value by adding your own data should be allowed, or just add the custom jinxes to the basic role.

I'm not sure which solution is better (completely replace standard jinxes or just add to it) but I'd love to be able to add jinxes!
have a good day

**Comment by bra1n** [comment]
Hey @AuroraKy, thanks for your suggestion, but this feature will not be added in the foreseeable future. Jinxes are meant to be _official_ rulings between 2 official characters. What you are describing is a Homebrew rule and should as such be treated differently, either by homebrewing one of the two characters involved or simply using the Bootlegger Fabled and announcing before the game, what homebrew rule you are using in conjunction with the characters on the script.
