### ISSUE TITLE
[BUG] Pulled out tabs snap to edge on secondary display

### ISSUE THREAD

**Issue by Pyrolithic** [ThePandemoniumInstitute/botc-release#174]
### Description

When using Firefox, if the window is on the secondary display, pulled out tabs, text, bluffs, etc. snap to the edge of the browser

If the right monitor is set to secondary display pulled out tabs snap to right edge of the browser, if the left monitor is set as secondary display pulled out tabs snap to left edge of the browser

If the browser is moved to the primary display, pulled out tabs can be positioned freely again

### Steps to reproduce

Open app in firefox
Move window to secondary disaply
Pull out tabs and try to position them

### Browser

Firefox

### Operating System

Windows

### Date and Time

28/04/24 20:30BST

### Game Session

tabsnap

**Comment by bra1n** [comment]
Thanks, I can confirm that this bug is happening on Windows only - on Linux & Firefox it works fine. I'll have to look some more into what is causing it, before I can fix it.

**Comment by bra1n** [comment]
This will be fixed with tomorrow's update!

**Comment by Pyrolithic** [comment]
Thanks
