### ISSUE TITLE
[BUG] Spectator is able to send message to public chat.

### ISSUE THREAD

**Issue by tsuite** [ThePandemoniumInstitute/botc-release#175]
### Description

Spectator is able to send spectator message to public chat tab. (v3.25.1)

### Steps to reproduce

1. Open text chat tab
2. Select Spectators Tab
3. Type message
4. Select Public Tab
5. Click send message button
6. Message appears in Public chat (probably only visible to spectators and storytellers)
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/8147792/ba9493d8-a54b-4356-9c9d-e419b4a8338e)

### Browser

Firefox

### Operating System

Windows

### Date and Time

2024-04-30 22:23 (+1000)

### Game Session

oce

**Comment by bra1n** [comment]
Thanks! While those messages were only visible to other spectators / STs, it still looks confusing. I'll fix it with the next update.
