### ISSUE TITLE
[BUG] Banshee - option to "put both hands up" 

### ISSUE THREAD

**Issue by StewieGriffin** [ThePandemoniumInstitute/botc-release#177]
### Description

In the new Banshee, the option to "put both hands up" is available to a dead Banshee regardless of how they've been killed (incuding killes not by the Demon)
That means a dead Banshee player can confirm themsleves regardless
They shouldn't be able to confirm themselves as Banshee by using the "put both hands up" button

### Steps to reproduce

Kill Banshee, by means other than the Demon
Click the button to "put both hands up" 

### Browser

Chrome

### Operating System

Windows

### Date and Time

April, 30 GMT

**Comment by bra1n** [comment]
Hi Stewie, thanks for the bug report, but this is not actually a bug. Check out #176 for the details.
