### ISSUE TITLE
[BUG] Failed night time

### ISSUE THREAD

**Issue by Azsael** [ThePandemoniumInstitute/botc-release#180]
### Description

Story tellers went to night but didn't go for night fdor players. Not sure how to repro sorry

### Steps to reproduce

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/13308772/785b952c-4adb-4e76-9b11-acbe9412ae4f)

### Browser

Chrome

### Operating System

Windows

### Date and Time

9:35PM

### Game Session

#seq

**Comment by bra1n** [comment]
Thanks for the bug report! Unfortunately, this has been a rather old and elusive bug, that's been hard to track down so far. I have been unable to reproduce it either. If you do find a way, please let me know! (and reopen the ticket)
