### ISSUE TITLE
Grimoire [BUG] 

### ISSUE THREAD

**Issue by Kayllain** [ThePandemoniumInstitute/botc-release#182]
### Description

Players in game are showing up as having the grimoire.

### Steps to reproduce

I am not sure how to repeat the bug, but the majority of players in the game saw the player as having the grim.  I know she was given the grim for the previous game before she became a player.

![Grimoire](https://github.com/ThePandemoniumInstitute/botc-release/assets/167394629/35f9733e-5f67-4318-bc59-a4617bc74b2b)

### Browser

Chrome

### Operating System

Windows

### Date and Time

May 26th, 5:30 pm CST

### Game Session

Beans

**Comment by bra1n** [comment]
Thanks for the bug report! I can confirm that this has been indeed an issue, but fortunately only a visual one - the player / user did not actually have access to the Grimoire at that point. The visual bug will be fixed with the next update!
