### ISSUE TITLE
[BUG] Reminder tokens visible to spectator without grim access

### ISSUE THREAD

**Issue by vaticidalprophet** [ThePandemoniumInstitute/botc-release#183]
### Description

I was spectating a public game and was able to view several reminder tokens before receiving grim access. When I eventually received grim access, these tokens disappeared, implying that they were left over from a prior game (they matched those seen in a previous game).

### Steps to reproduce

Have not been able to replicate

### Browser

Firefox

### Operating System

Windows

### Date and Time

April 3rd 2024, ~11pm UTC+09:30

**Comment by bra1n** [comment]
Hi @vaticidalprophet, do you remember whether some of the players in the new game / session were also present in the previous game / session, from which the reminder tokens remained?

**Comment by bra1n** [comment]
Closed due to inactivity.
