### ISSUE TITLE
Character Token not showing in game[BUG] 

### ISSUE THREAD

**Issue by PartyPual** [ThePandemoniumInstitute/botc-release#184]
### Description

When assigned a role, the role toke is not shown. There is a border shown that is blue or red depending on the team, but a blank token instead of a specific role. Checking streamer mode tokens, show alignment on town square is enabled
![botc grab](https://github.com/ThePandemoniumInstitute/botc-release/assets/171756873/de6feeff-c78a-4909-95c6-24888a04c65d)
In endgame, after character reveal, no roles are visible, only the red and blue borders.
![botc endgame](https://github.com/ThePandemoniumInstitute/botc-release/assets/171756873/f4e04ebf-0451-4076-a03f-054671cbec38)

As per text copied below, the role is shown in the f12 code but not by the token on the screen.

<div data-v-56640ad1="" data-v-bcc9e3ca="" class="token role-fisherman edition-custom team-townsfolk"><span data-v-56640ad1="" class="icon" style="background-image: url(&quot;/img/fisherman_g.f035fbc8.webp&quot;);"></span><span data-v-56640ad1="" class="leaf-top leaf-top1"></span><svg data-v-56640ad1="" viewBox="0 0 150 150" class="name"><text data-v-56640ad1="" x="66.6%" text-anchor="middle" class="label mozilla" font-size="110%"><textPath data-v-56640ad1="" xlink:href="#half-circle-path">Fisherman</textPath></text></svg><div data-v-56640ad1="" class="ability">Once per game, during the day, visit the Storyteller for some advice to help your team win.</div></div>

### Browser

Chrome

### Operating System

Windows

### Date and Time

Every time I play, since the change to the new app

### Relevant console log output

Copy pasted error log output, see also screenshots for image of error message
![botc error](https://github.com/ThePandemoniumInstitute/botc-release/assets/171756873/539e9c3e-9540-4f3b-86d8-8ba10b305393)

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(222, 227, 229); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="https://botc.app/js/app.3026db38.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">app.3026db38.js:1</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">2nd try consuming error 7464579235994 <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><div style="box-sizing: border-box; min-width: 0px; min-height: 0px;">InvalidStateError: closed
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at z.consume (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://botc.app/js/chunk-vendors.b2290157.js:29:93703" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">chunk-vendors.b2290157.js:29:93703</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at pb.getConsumeStream (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://botc.app/js/app.3026db38.js:1:470216" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">app.3026db38.js:1:470216</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async pb.consume (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://botc.app/js/app.3026db38.js:1:469327" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">app.3026db38.js:1:469327</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Be.&lt;anonymous&gt; (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://botc.app/js/app.3026db38.js:1:465424" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">app.3026db38.js:1:465424</button>)</span></div></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(222, 227, 229); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 483px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | (anonymous) | @ | app.3026db38.js:1
-- | -- | -- | --

</span></div>
</body>
</html>

Note: the error codes were not present after clearing cache and cookies, but the problem persisted with no changes.

**Comment by bra1n** [comment]
Hey @PartyPual, thanks for the bug report! If you take a closer look at the center of the town square, you'll notice that there is a hint that tells you to press "T" to return to the grimoire view. :wink: It looks like you somehow (accidentally) switched to the town square view, which only shows you the life / vote tokens of the players in your game.
