### ISSUE TITLE
[BUG] The bug hand emote does not show up at all if you have animations disabled

### ISSUE THREAD

**Issue by moutonf** [ThePandemoniumInstitute/botc-release#186]
### Description

During a game a player was talking about the bug report hand that one can earn from reporting a bug. I have animations disabled and noticed that the hand is not visible to me at all. I assume there is just not a version of a still image for it, and thus it displays nothing.

### Steps to reproduce

1. Disable animations in settings
2. Use bug hand
3. Bug hand should not be visible

### Browser

Chrome

### Operating System

Mac

### Date and Time

10 June 2024 @ 18:00, UTC+2

### Game Session

#smile

### Relevant console log output

```shell
N/A
```

**Comment by bra1n** [comment]
Thanks, this will be fixed with the next update!
