### ISSUE TITLE
[BUG] Show bluffs tab does not work in Teensyville without Toymaker as a player

### ISSUE THREAD

**Issue by jakubmplatek** [ThePandemoniumInstitute/botc-release#187]
### What problem are you trying to solve?

When the game is played without bluffs (as in Teensyville), the Bluffs tab is not available, even if the "Show Bluffs Tab" option is enabled in settings. The tab is useful for tracking bluffs or otherwise out-of-play characters regardless if you play as a demon or not.

### Describe the solution you'd like

Make the "Show Bluffs Tab" option in settings override the default visibility of the Bluffs tab.

**Comment by bra1n** [comment]
Alright, this will be in today's update, finally! Sorry that it took us this long...
