### ISSUE TITLE
[BUG] Spectator to Storyteller still has grim access icon

### ISSUE THREAD

**Issue by TrappedCosmos** [ThePandemoniumInstitute/botc-release#188]
### Description

Title basically says it all, when a spectator with grim access became added as a storyteller the grim access icon remained.

### Steps to reproduce

1. Give a spectator grim access
2. Promote them to Storyteller
3. Check Menu

### Browser

Standalone app

### Operating System

Windows

### Date and Time

June 21, 2:09 Pm Central Daylight Time

### Game Session

https://botc.app/join/findtheimp

**Comment by bra1n** [comment]
Thanks, I'll fix this soon!

**Comment by bra1n** [comment]
Alright, this will be fixed with the next update!
