### ISSUE TITLE
[FEATURE] Spy/Widow copy Grim.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#189]
### What problem are you trying to solve?

As something with Grim-access you always have to manually copy all the characters from the message you get to your grim, which isn't much of a problem, but for QoL purposes it would be great to have way to speed it up.

### Describe the solution you'd like

A button in the grim window the Spy/Widow gets that makes it possible to just copy the grim you got send entirely, overwriting whatever you had in your grim.

**Comment by bra1n** [comment]
Hi Unbaloav,
this functionality was intentionally left out of the app, in order to not make it too easy for the Spy to copy the full Grimoire, to keep it a bit closer to the physical game, where you also cannot simply make a copy of what you're seeing as the Spy / Widow.
