### ISSUE TITLE
[BUG] Microphone

### ISSUE THREAD

**Issue by masl0809** [ThePandemoniumInstitute/botc-release#190]
### Description

When you unmute the muted icon stays there

### Steps to reproduce

1. Join a lobby
2. Sit down
3. Open mike
4. Leave lobby
5. Join a second lobby
6. Sit down
7. Unmute
When you unmute the muted icon stays there

### Browser

Safari

### Operating System

Mac

### Date and Time

3am UTC 4:00 June 28,2024

**Comment by bra1n** [comment]
Hi @masl0809,
thanks for the bug report! This is indeed an issue that got introduced recently. The app shows that you are unmuted while you actually are muted, so the first try to mute will in reality align the visual indicator with the internal app status - making it look like nothing happened. I'll fix this with the next update!

**Comment by masl0809** [comment]
Hey! I have a question for you. By reporting the bug, do I get the smack a
bug hand? I saw some players online that said they got it after reporting
one.

**Comment by bra1n** [comment]
Hey, sure, as soon as it's actually fixed! Just send me an email to support@botc.app or DM me on Discord (same username) with your app user ID or email address. :-)

**Comment by masl0809** [comment]
Perfect. I'll send the user ID, username, and my address just in case.

ID: 7516378759322
E-mail: ***@***.***
Username: MASL0809

**Comment by bra1n** [comment]
Sure thing, gave you the ability!
