### ISSUE TITLE
[BUG]  Dead Banshee given ability to raise two hands when not demon-killed

### ISSUE THREAD

**Issue by scottisongithub** [ThePandemoniumInstitute/botc-release#192]
### Description

In two different instances a Banshee was able to validate that they were given a Banshee token by raising two hands in the voting phase, when they had not triggered the Banshee ability. 

- once when a Banshee was executed and then on future days was able to raise two hands to vote 
- second, a Marionette-Banshee was killed by the Demon at night, but was still able to raise two hands to vote in the future

In neither occasions was the Banshee reminder token added to the grimoire.

---

Perhaps the ability to raise two hands should be tied to the Banshee ability instead of, seemingly, being tied to the role token

### Steps to reproduce

1. Begin a game with a banshee
2. Execute the Banshee 
3. The dead Banshee is given the ability to raise two hands in future votes

### Browser

Standalone app

### Operating System

Windows

### Date and Time

29th June 2024, 7pm AWST

### Game Session

-

### Relevant console log output

```shell
-
```

**Comment by bra1n** [comment]
Hi @scottisongithub,

thanks for your report! What you describe is actually the intended behaviour - just like in RL games, anyone that claims to be the Banshee can raise two hands if they'd like. The Storyteller will still only count one of them and remove the ghost vote token if they are not the Banshee. The same happens in the app: if you are dead and assign yourself the Banshee token, you will be able to put up both hands. But that doesn't grant you the double vote and if you try it, you'll see that you just spent your ghost vote token on a single vote.
So seeing someone in game raising both hands doesn't mean they actually are the Banshee or have the ability. If the Storyteller did not announce that someone is a Banshee, they might be able to raise both hands, but they will not get the double vote ability.
