### ISSUE TITLE
[BUG] Vote History is off

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#197]
### Description

![grafik](https://github.com/user-attachments/assets/aeafc6d8-4fcc-46af-9139-ab9b1267beb8)
The numbers about how many votes and what the majority is don't add up on day 2 and 3.
On day 3 I remember that the very first nomination doesn't show up.

### Steps to reproduce

I have no idea, why it might have happened.

### Browser

Standalone app

### Operating System

Windows

### Date and Time

July 18th, 4PM GMT

### Game Session

simpleandfun

**Comment by bra1n** [comment]
Hey @Unbaloav, thanks for the bug report, but I'd need more information. What exactly is wrong there? The data in the screenshot itself seems to be fine? What should have been shown there? How did you arrive at the "broken" state?

**Comment by Unbaloav** [comment]
Oh, sorry. I think I misunderstood the Majority Column. I thought it would be showing the current majority and not the minimum amount needed for someone to be executed. On the 3rd day we had one nomination before the first in the history, that had 4 votes, but didn't show up in the history. Probably the ST just made an error by accident, like cancelling the nom and marking them again.

**Comment by bra1n** [comment]
Fair enough, thanks for clarifying! Yeah, maybe the ST cancelled the vote before it was complete.
