### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hedineijenhuis** [ThePandemoniumInstitute/botc-release#198]
### Description

Joined a private session -  I could take a seat, but besides names nothing else loaded. Data from previous game on one person was still showing.  Error message showing was this:

![Screenshot 2024-07-20 201611](https://github.com/user-attachments/assets/80989d65-4e67-4269-8391-e00ebe6a8a12)

Did a clear cache and hard reload, did not work. Once clearing cache separately in google chrome it fixed the issue. 

### Steps to reproduce

1. Error upon taking seat. 

### Browser

Chrome

### Operating System

Windows

### Date and Time

20th July 2024, 8PM GMT

### Game Session

#sww

**Comment by bra1n** [comment]
Hey there, thanks for the bug report! Does the error still happen? Otherwise, it was probably some weird glitch, maybe caused by outdated app data. I'm glad that you got it fixed - if it happens again, could you please take a screenshot of the app in the bugged state?
