### ISSUE TITLE
[BUG] Fullscreen in server list

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#200]
### Description

You can't switch fullscreen mode in the server lobby.

### Steps to reproduce

1. Open the app.
2. Press your Fullscreen button.

### Browser

Standalone app

### Operating System

Windows

**Comment by StewieGriffin** [comment]
I've just tried both on Chrome and Firefox, and fullscreen (in the server lobby and in-game) works as it should.

**Comment by bra1n** [comment]
Hey there, this has been indeed an oversight - with the next update, switching to full screen will be possible from the Lobby screen as well.
