### ISSUE TITLE
[FEATURE] Display living players as Residents + Travellers

### ISSUE THREAD

**Issue by Shad0wSlam** [ThePandemoniumInstitute/botc-release#201]
### What problem are you trying to solve?

Checking how many players are alive, for the purposes of being aware of final 3, is inaccurate in the Alive tally.
Checking requires players to either manually tally the living residents around the circle or remember that Travellers are included in the count and remove their count. While the count is mechanically accurate, it's often not the information players want (say, checking if players should be executing or sleeping today).

### Describe the solution you'd like

Displaying the Alive value as "[Living Residents] (+ [Living Travellers])" would solve the problem, as if players need to know total living players, they can simply add the numbers together, whereas if they need to know living residents they can easily check the main number. For additional clarity, the Traveller number could be in the Traveller purple used for the Traveller count.

### Alternatives you have considered

Players could be confused with what the (+ Number) means, so perhaps including it in the lower Traveller section would work instead. This does however split up the Alive info, which seems potentially confusing.  This does however keep the Alive column compact, so depending on the importance there this might be preferred.

**Comment by bra1n** [comment]
Hey there, thanks for the suggestion, the next update will change the central info box to look like this:
![image](https://github.com/user-attachments/assets/09aba0eb-d3e7-44c3-a2d8-5eb91210f9ad)
