### ISSUE TITLE
[BUG] Condensed script mode displays text off screen resulting in large character spacing

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#205]
### Description

When the script is in condensed mode and collapsed for just character names, the character ability text is still "displayed" off the screen resulting in spacing between characters to be based on the text formatting of the ability. This can result in odd spacing on smaller resolutions where the text wraps more than the standard character sizing.

1920x1080
![image](https://github.com/user-attachments/assets/4e4c5ecd-7178-41ca-abd0-1510b1cecc5b)
![image](https://github.com/user-attachments/assets/2336b641-543f-4600-bdc1-7eedb4d6918a)

1680x1050
![image](https://github.com/user-attachments/assets/fa01fc73-6d1e-4553-877e-f535f1245c96)
![image](https://github.com/user-attachments/assets/0c98fb9a-ec76-459e-8bff-3e8b92e8a1ae)

In 1680x1050 the General ability text wraps to 3 lines, causing the condensed view of character names to have large spacing.

### Browser

Chrome

### Operating System

Windows

### Date and Time

Irrelevant

**Comment by bra1n** [comment]
Thanks for the report! With the next update, the ability text will be shrunken down further when the tab is only half-open, so that the names don't take up more space than they need to.
