### ISSUE TITLE
[FEATURE] More visible timer.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#206]
### What problem are you trying to solve?

When you have some remindertokens on a player, especially when there are few players they quickly reach into the middle of the screen making the timer unreadable sometimes. (for me usually only a problem on the final day)

### Describe the solution you'd like

An option to always have the timer (additionally) be displayed in the bottom right, just the way it is currently displayed when you are in a chat with someone with an active camera.

### Alternatives you have considered

Having the timer be a movable frame, just like the voice, text and bluffs tabs.

**Comment by bra1n** [comment]
The next version update will allow you to enable reminder token stacking even when there are no avatars / cams, so that you can get at least some extra space in the middle of the Grimoire to show the timer. Making it movable would be a lot of extra work, so that's not feasible right now.
