### ISSUE TITLE
[BUG] Remindertokens and Character of ST lost on reconnect.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#212]
### Description

When you have a character or a note on the ST as a player / spectator and you reconnect they are deleted from your grim. 
(Additionally I lost my entire grim when I was in a game and tested it as a spectator in a different game and then coming back, but I asssume that is intended.)

### Browser

Standalone app

### Operating System

Windows

### Date and Time

{time of submission}

**Comment by bra1n** [comment]
Good find, thanks! This will be fixed with the next update.
