### ISSUE TITLE
[FEATURE] Add more prominent indication of when a user is speaking

### ISSUE THREAD

**Issue by Killectro** [ThePandemoniumInstitute/botc-release#215]
### What problem are you trying to solve?

It's often difficult (in both the old and new interfaces) to tell when a certain user is speaking. Often someone will say something and my eyes won't have time to scan the entire circle to see who was talking if I'm not already familiar with everyone's voice.

### Describe the solution you'd like

I'd love a more prominent/scannable/noticeable indication of when someone is speaking so that the indicator will draw my eye to it rather than my eye having to scan around to find it. How should it look? I have no clue!

**Comment by bra1n** [comment]
Thanks for the suggestion, this is indeed something that I plan to improve soon!
