### ISSUE TITLE
[BUG] It's possible to see when the storyteller is muting/unmuting in the nighttime

### ISSUE THREAD

**Issue by Killectro** [ThePandemoniumInstitute/botc-release#217]
### Description

It is possible for players to see whether the storyteller is muted during the nighttime by looking at the layout of the storyteller's name plate. The text is center-aligned when the ST is unmuted and not center-aligned when the ST is muted.

| Muted | Unmuted |
|--------|--------|
| <img width="127" alt="Screenshot 2024-09-05 at 15 45 08" src="https://github.com/user-attachments/assets/531644ce-b4e0-489d-bb23-61f1a0d07a25"> | <img width="130" alt="Screenshot 2024-09-05 at 15 08 07" src="https://github.com/user-attachments/assets/32a1e5e5-1465-4ef5-8ef0-9852a342a008"> | 

### Browser

Chrome

### Operating System

Mac

### Date and Time

Sept 5 2024 any time EST

**Comment by bra1n** [comment]
Hey @Killectro, this should not be visible to players. The mute icon is only shown if you are muting yourself. Any player should not see a ST mute icon during the night phase. I've tested it on the live version just now and the players in the session will only ever see the voice activity indicator, but not the mute status.
