### ISSUE TITLE
[BUG] Error that caused character tokens to be messed up

### ISSUE THREAD

**Issue by apophisnow** [ThePandemoniumInstitute/botc-release#218]
### Description

Randomly after a game the character tokens became messed up.

### Steps to reproduce

Unknown, but probably when ST was adjusting seats and people were leaving and joining the lobby.
<img width="1107" alt="Screenshot 2024-09-05 at 10 12 22 PM" src="https://github.com/user-attachments/assets/56e08df0-0bc6-463c-bacd-24f5aadffd8f">

### Browser

Chrome

### Operating System

Mac

### Date and Time

2024-09-06T04:39:38.637Z

### Game Session

https://botc.app/join/stuffnthings

### Relevant console log output

```shell
2024-09-06T04:39:38.637Z - chrome 127.0.0 Mac OS - #stuffnthings
TypeError: Cannot set properties of null (setting 'value')
    at Proxy.handleAvatarUpload (https://botc.app/assets/index-zlelDgJd.js:9:48282)
```

**Comment by apophisnow** [comment]
The issue persists after a refresh of the page as well.

**Comment by bra1n** [comment]
That's not a bug, but the way it currently looks like - empty seats / disconnected players won't show an avatar. This will be changed with the next update, however.

**Comment by apophisnow** [comment]
My expectation is that they would be the same size as the other tokens. No problem with them not showing an avatar.

**Comment by bra1n** [comment]
Agreed, which is why this will be changed in the upcoming update. :-)
