### ISSUE TITLE
[BUG] Full screen not working

### ISSUE THREAD

**Issue by sgcouk** [ThePandemoniumInstitute/botc-release#219]
### Description

Shortcut key is set to default F, when using the app the Full screen function doesn't work via either the short cut key or by using the menu option

### Browser

Standalone app

### Operating System

Windows

### Date and Time

6th September 2024 17:12 UTC

**Comment by bra1n** [comment]
Hey there, thanks for the bug report! This will be fixed in the next update. :-)
