### ISSUE TITLE
[BUG] [mobile]Patreon Scroll Image incomplete 

### ISSUE THREAD

**Issue by nichtsalsflousen** [ThePandemoniumInstitute/botc-release#220]
### Description

The scroll of Patreon supporters is not displayed correctly on the mobile version.
![IMG_20240907_211516](https://github.com/user-attachments/assets/323fb7ad-e3a2-421e-b67d-fe206603e5a2)

### Steps to reproduce

Open the app on a mobile phone (android)

### Browser

Chrome

### Operating System

Android

### Date and Time

September 7.

**Comment by bra1n** [comment]
Thanks, but there is currently no official support for mobile.
