### ISSUE TITLE
[BUG] Show player cosmetics setting leads to inconsistent UI

### ISSUE THREAD

**Issue by apophisnow** [ThePandemoniumInstitute/botc-release#221]
### Description

I have disabled player cosmetics because player borders that are blue cause the microphone icon to be hard to see (low contrast). Now when looking at which avatar I have selected it shows the default avatar even though that is not what is being shown to other players (i uploaded a custom one). This is confusing because I have no way to tell what avatar is being displayed to others when this setting is off.

My recommendation would be to show the currently selected avatar in the settings menu, but keep the grim the way it is.

### Steps to reproduce

Select a non default avatar.
Turn off player cosmetics.
The avatar shown in settings no longer matches what others see.

### Browser

Chrome

### Operating System

Mac

### Date and Time

Sep 7 19:00 PST

**Comment by bra1n** [comment]
Good find, this will be fixed in the next update!
