### ISSUE TITLE
[BUG] Butcher nominations don't reflect the correct majority

### ISSUE THREAD

**Issue by scottisongithub** [ThePandemoniumInstitute/botc-release#223]
### Description

When the Butcher traveler is in play the execution granted by their power shows the incorrect number of votes needed for majority. Currently it will treat it as though it is just a normal nomination, taking into considering the past number of votes and the amount needed to tie. It should instead be just a majority of the alive players.

> To succeed, this nomination must tally votes of at least half the alive players, as normal, but does not have to exceed the votes of the execution that prompted the Butcher ability.
-- https://wiki.bloodontheclocktower.com/Butcher

Perhaps it could trigger a change in the nomination requirements after someone is nominated and dies?

### Steps to reproduce

- Create a game with 10 people including one Butcher traveler
- Execute a townsfolk with a vote of 7. They die.
- The Butcher can now nominate another person.
- The nomination box will state 7 needed for a tie, 8 to execute. 
  - It should just say that 5 are needed to execute (majority for the 9 alive, it cannot tie).

### Browser

Standalone app

### Operating System

Windows

### Date and Time

11/9/2024

### Game Session
Session id: PLAW
Majority for the butcher nomination should be 6 when 11 was alive.

![plaw](https://github.com/user-attachments/assets/83aea2d1-1878-48cc-b3f0-ac3c19664894)

**Comment by bra1n** [comment]
Hey there, this isn't a bug, but just something that the app isn't supporting at the moment. The next update will allow the ST to change the vote highscore, though, making it possible for them to reset it for a Butcher nomination.
