### ISSUE TITLE
[BUG] Blood moon rising Character sheet

### ISSUE THREAD

**Issue by coupmaster09** [ThePandemoniumInstitute/botc-release#224]
### Description

Sometimes Po on the character list shows up with the title of actor instead of po

### Steps to reproduce

When I loaded in the demon Po was titled Actor in the character sheet, when i reloaded it fixed itself

### Browser

Chrome

### Operating System

Windows

### Date and Time

9/13/24

### Game Session

I dont know how to find this

### Relevant console log output

```shell
index-C82-D0ul.js:10 Access denied for video:  NotFoundError: Requested device not found
```

**Comment by pattersttv** [comment]
Hi there,

Thanks for reporting this. Would you be able to provide me with your account ID?
You can do this by pressing Q and to the Users tab, the ID should be in the middle top of the popup.

Thanks,
Patrick

**Comment by coupmaster09** [comment]
My account ID is 7755816665242

**Comment by bra1n** [comment]
We weren't able to reproduce it, so I'm closing this.
