### ISSUE TITLE
[BUG] Last role showed up incorrectly after game swap

### ISSUE THREAD

**Issue by drewv1234** [ThePandemoniumInstitute/botc-release#225]
### Description

After finishing a game of Sects and Violets, we switched the mode to Bad Moon Rising, switched storytellers, and added a couple seats. In the first night, I was reading the roles (first time playing this ruleset), and was asking friends about the "After" role. Turns out, there was no "After" role - the last role on the list (the Po role) was mislabeled. It was only mislabeled for me - none of my other friends had this issue. Refreshing the page fixed the issue.

### Browser

Chrome

### Operating System

Windows

### Date and Time

9/13/2024 7:40 PT

### Game Session

7603

### Relevant console log output

```shell
https://cdn.discordapp.com/attachments/1264282283880353814/1284344096567328870/image.png?ex=66e64a26&is=66e4f8a6&hm=77ecb95120aa8d691019860883bb5328d7b432096b3ef4c8116346e9c5f4fb9e&
```

**Comment by pattersttv** [comment]
Hi Drew,

Thanks for reporting this. Would you be able to provide me with your account ID?
You can do this by pressing Q and to the Users tab, the ID should be in the middle top of the popup.

Thanks,
Patrick

**Comment by bra1n** [comment]
Closed due to inactivity
