### ISSUE TITLE
[BUG] The town breakdown info

### ISSUE THREAD

**Issue by Maxlee1255** [ThePandemoniumInstitute/botc-release#227]
### Description

As the story teller when you're trying to add reminder tokens the town info screen continues to pop up, this might be more an issue for those like myself on laptops that have smaller screens but it can be a bit frustrating when you're trying to add reminders and having to be very precise as not to have that menu pop up. 
It would be nice maybe as just a shortcut key for those that have smaller screens. 
I will say though that I've not had this issue before, it seems to be in one of the more recent updates it now pops up when you haven't flipped the tokens using "T"
![image](https://github.com/user-attachments/assets/f67c10a1-8271-47e4-a3cd-e325ce0223f1)

### Steps to reproduce

go to add reminder token on the inside of town circle
go anywhere in the circle near the edges and it still pops up

### Browser

Chrome

### Operating System

Windows

### Date and Time

14/09/24 16:00 GMT 0

### Game Session

https://botc.app/join/beginners

### Relevant console log output

```shell
Not sure if I have to add my username anywhere but it's Maxlee in game usually.
```

**Comment by bra1n** [comment]
Thanks, this will be updated / fixed today!
