### ISSUE TITLE
[BUG] Avatar causing issues 

### ISSUE THREAD

**Issue by Pratyush0015** [ThePandemoniumInstitute/botc-release#228]
### Description

After the recent update whenever I join from mobile and enter into private whisper Avatars used to block the grim making it impossible to see some character tokens and add reminder tokens. Specially when I logged in from my phone while Storytelling with one of my friend I was unable to add reminder tokens or see other reminder tokens as view was blocked by two Avatars in the middle of screen.

### Steps to reproduce

1. Join any session with android device.
2. Send chat request to someone and enter into private that.
3. Try adding a reminder token on grim pure.
4. Try removing Avatars from middle of screen.

### Browser

Chrome

### Operating System

Android

### Date and Time

14 sept 2024

### Game Session

Guddu

**Comment by pattersttv** [comment]
Hi Pratyush,

Currently the application does not support mobile devices so the experience is likely to be poor at this time.

Thanks,
Patrick

**Comment by Pratyush0015** [comment]
But my mobile supports your application and I can do everything a pc used can using mobile. Your application actually supports mobile devices and it was since you fixed a issue of arranging grim by considering screen size. It was perfectly fine till now.  But this recent update is actually terrible. And I am very disappointed with it.

**Comment by bra1n** [comment]
You can always disable avatars / cams altogether, to get back to the old layout if you prefer. There's a setting in the "Advanced" tab for this.
