### ISSUE TITLE
[FEATURE] Add voice level indicators to non-avatar mode

### ISSUE THREAD

**Issue by Pratyush0015** [ThePandemoniumInstitute/botc-release#229]
### Description

When I disable the Avatars by going to settings. So I can only see the character tokens on  full screen. It dont start showing audio visuals (when someone speaks) at there character tokens makes impossible to see who is speaking. Since our group plays botc without camera on. And Avatars are kind of taking some space so we prefer turn them off.

### Steps to reproduce

1. Join a game session.
2. Go to settings disable avatars.
3. Try to figure our who is speaking by looking at screen.

### Browser

Chrome

### Operating System

Android

### Date and Time

Sept 14, 10pm IST

### Game Session

Guddu

**Comment by bra1n** [comment]
Hi, this isn't exactly a bug, but rather something that needs to be improved. There is still the "is speaking" color change of the user names to determine who is currently speaking, although the voice level indicators are missing currently when the avatars are hidden. We have plans to add those back into the non-avatar version of the app as well, but it'll take a bit more time!

**Comment by bra1n** [comment]
This is live now!
