### ISSUE TITLE
[BUG] Spectators Names look weird in lobbies

### ISSUE THREAD

**Issue by akshat1512** [ThePandemoniumInstitute/botc-release#231]
### Description

Spectators names are visibly a bit weird. For Example Peanut butter is one name - but its stretching across 2 lines, and then the next name starts.

<img width="857" alt="image" src="https://github.com/user-attachments/assets/b8813d4d-e9d9-4437-b64d-3a3ebddb8580">

### Browser

Chrome

### Operating System

Windows

### Date and Time

16 Sep 7.30 pm IST

### Game Session

89240

**Comment by bra1n** [comment]
Thanks for the bug report! This was indeed a small visual issue, which will be fixed with the next update. :-)
