### ISSUE TITLE
[BUG] Avatars not showing in private chats

### ISSUE THREAD

**Issue by CreativeMod1** [ThePandemoniumInstitute/botc-release#232]
### Description

When in a private chat with players who don't have cameras on, it's meant to show the avatars of said players.
This doesn't show and instead it just shows a blank screen

### Steps to reproduce

1) Switch off cameras
2) Go into a private chat

### Browser

Chrome

### Operating System

Windows

### Date and Time

12th September 8pm GMT

**Comment by bra1n** [comment]
This has already been fixed.
