### ISSUE TITLE
[BUG] When using Baker nominations, the nominator is not indicated

### ISSUE THREAD

**Issue by Shad0wSlam** [ThePandemoniumInstitute/botc-release#233]
### Description

When using the Baker nomination setting, the grey arrow that normally appears to point at the player who nominated does not appear.

### Steps to reproduce

1. In a lobby, set the nomination type to Baker.
2. Have a player nominate another player.
3. Note that the gold arrows point at the nominated player, but not the grey arrow for the nominator.

### Browser

Chrome

### Operating System

Windows

### Date and Time

September 16th, 8pm BST

### Game Session

#placingblocksnshit

**Comment by bra1n** [comment]
This is not a bug, but the intended behavior. Originally, Clocktower was meant to be played so that only the accused would be allowed to make a statement, and the Baker mode reflects that. The nominator will have neither a clockhand arrow, nor a visual highlight.

**Comment by Shad0wSlam** [comment]
I feel like it's an unhelpful change though then. The grey arrow doesn't direct people's attention, but what we did have was the moment it was used, people were confused about who exactly nominated (particularly for things like Town Crier), including the nominator. Maintaining the grey arrow, which is subtle, while still having the other focus features of Baker is what I expected, particularly given the description of Baker doesn't indicate any visual changes.

**Comment by bra1n** [comment]
Fair enough, I'll think about it. :-)
