### ISSUE TITLE
[BUG] Avatars still shows in private chat when turned off

### ISSUE THREAD

**Issue by Pratyush0015** [ThePandemoniumInstitute/botc-release#234]
### Description

Even after turning off Avatars in setting, it shows in private chats. The setting only applies to town square.

### Steps to reproduce

1. Join a game.
2. Go to setting>advance turn off Avatars.
3. Join private chats 
4. Avatars are still there.

### Browser

Chrome

### Operating System

Windows

### Date and Time

Sept 18, 01:00am IST

**Comment by bra1n** [comment]
Hi, this is not a bug, but intended. The setting in the options specifically only mentions disabling the avatars / cams _on the town square_ for this reason.
