### ISSUE TITLE
[FEATURE] Hide single players custom avatar.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#236]
### What problem are you trying to solve?

I was in a game with someone that had a .gif as their avatar which had really hurt my brain, making it hard to concentrate because there was too much movement on my screen.

### Describe the solution you'd like

Would be great to be able to deactivate a single persons custom avatar, the same way you can click 'Hide Camera' on someone.
(I deactivated Show Player Cosmetics, but I generally like having the cosmetics showing.)

**Comment by bra1n** [comment]
Thanks, this will be added with this week's update!
