### ISSUE TITLE
[BUG]  Weird issue where hovering mouse between character token and reminder tokens cause them to co crazt

### ISSUE THREAD

**Issue by BizMcFiz** [ThePandemoniumInstitute/botc-release#237]
### Description

As I was playing using the latest build of the app I found that when hovering my mouse just outside of the character token, with multiple reminder tokens you can make the tokens violently vibrate on screen.

Example video (apologies it's really brief, I was on stream at the time):  https://youtu.be/v6duFt8EN0c

### Steps to reproduce

1. Start a game
2. Have multiple reminder tokens
3. Move your mouse to just outside of the character token, in the centre of the reminder tokens.

### Browser

Opera

### Operating System

Windows

### Date and Time

Sept 22, 2024 20:35 GMT

### Game Session

#helle

**Comment by BizMcFiz** [comment]
NP, hardly a game-breaking bug but thought it'd be worth throwing on a backlog 🤣

**Comment by BizMcFiz** [comment]
(Also, having revisited, apologies for the misspelled title Bra1n... that may mean nothing to you but damn does it break me!)

**Comment by bra1n** [comment]
No worries. :laughing:
