### ISSUE TITLE
[BUG] Vote bug with multiple Storytellers

### ISSUE THREAD

**Issue by Kikka12** [ThePandemoniumInstitute/botc-release#241]
### Description

Current version v3.33.0
If there are two (and I think more) Storytellers in the game, and one of them starts a nomination, then click on the Close button and the other on the Start button almost at the same time, then the vote menu is closed for either or both ST, but the vote goes through and stays on the vote screen without the menu to close it, we couldn't find a way to fix it, the only solution is a new lobby or to remove one of the ST and the other to refresh the page (or at least it worked for us now)
tried in a new lobby too, and the bug is reproducible

### Steps to reproduce

create a lobby
get 2 STs
start a vote
click on the close and the start button at the same time
see that the menu is closed and the vote is going at the same time

### Browser

Chrome

### Operating System

Windows

### Date and Time

September 29, 23:00 GMT+2

### Game Session

36380 and 5204

### Relevant console log output

```shell
Don't know it has anything to do with this but this is the only console error:

Error closing producer Error: socket has been disconnected                     index-BojIW9jb.js:1124
    at vendor-CnnSja4F.js:793:166031
    at Array.forEach (<anonymous>)
    at bb._clearAcks (vendor-CnnSja4F.js:793:165906)
    at bb.onclose (vendor-CnnSja4F.js:793:165857)
    at bb.disconnect (vendor-CnnSja4F.js:793:167940)
    at ET.disconnect (index-BojIW9jb.js:1123:61794)
    at async index-BojIW9jb.js:1124:13814
```

**Comment by bra1n** [comment]
Hi @Kikka12, this very same issue has already been reported by another user in your session! :-D See #240

**Comment by Kikka12** [comment]
Hi, yes I know we were the 2 Storytellers who found the bug after a game he run, and he told me to report it on here, and he reported it on the Standalone platform, but he was faster and it went to the same issue tracker, when you can fix it, can we both get the "bug feature" easter egg for the game?

**Comment by bra1n** [comment]
Sure, just DM me your app user ID or post it here. :-)

**Comment by humanpala** [comment]
Hello. Thank you the fix.
my ID: 6415215591578
