### ISSUE TITLE
[BUG] Typo in free tier explanation.

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#242]
### Description

![grafik](https://github.com/user-attachments/assets/4d5c456f-bd89-4187-9c00-3f26e2d3442a)
The 'Y' of "You" is swapped with the space that should be to its left.

### Browser

Standalone app

### Operating System

Windows

### Date and Time

{time of submission}

**Comment by bra1n** [comment]
Thanks, this will be fixed with the next update. :-)
