### ISSUE TITLE
[BUG] Sound effects lost on update

### ISSUE THREAD

**Issue by Simmyish** [ThePandemoniumInstitute/botc-release#243]
### Description

I was playing a game on the app and during the game it update during the game, and the sound effects stopped working specifically after the update, all individual sound settings are at 100%
![image](https://github.com/user-attachments/assets/8b6b34e4-6e71-492c-bbf2-9682163ee16a)
![image](https://github.com/user-attachments/assets/d1edec90-d54a-49bb-9ac6-e23cb751d847)

### Steps to reproduce

1. Update game to 3.31-1
2. Enter a game, and run a timer
3. There is no sound on the gong for the timer or recall to town square

### Browser

Standalone app

### Operating System

Windows

### Date and Time

30th September 2024/15:00

### Game Session

https://botc.app/join/colon%20three

### Relevant console log output

```shell
index-XjxxBX-d.js:10 trigger true <ul data-v-aa0dec81 id=​"whispers" class=​"small" draggable=​"true" style=​"--volume6845638443162:​ 0;​ --volume7780760649882:​ 0;​ --volume7575934206106:​ 0;​ --volume7752707145882:​ 0;​ --volume7577884557466:​ 0;​ --volume6701935067290:​ 0;​ --volume7580020834458:​ 16;​ --speaking7580020834458:​ 0;​ --speaking6845638443162:​ 0;​ --speaking6701935067290:​ 0;​ --speaking7752707145882:​ 0;​">​<li data-v-aa0dec81 class=​"video" style=​"z-index:​ 20;​ --speaking:​ var(--speaking6845638443162)​;​ --volume:​ var(--volume6845638443162)​;​">​…​</li>​<li data-v-aa0dec81 class=​"video dead flag-powerful" style=​"z-index:​ 19;​ --speaking:​ var(--speaking7580020834458)​;​ --volume:​ var(--volume7580020834458)​;​">​…​</li>​<li data-v-aa0dec81 class=​"video storyteller" style=​"z-index:​ 18;​ --speaking:​ var(--speaking7791657648282)​;​ --volume:​ var(--volume7791657648282)​;​">​…​</li>​</ul>​
index-XjxxBX-d.js:10 trigger false null
```

**Comment by bra1n** [comment]
Hi, thanks for the bug report, this has been fixed with a hotfix earlier today.
