### ISSUE TITLE
[Bug] Boffin Banshee interaction 

### ISSUE THREAD

**Issue by VidyutBalaji** [ThePandemoniumInstitute/botc-release#244]
### Description

When the demon was given the banshee ability due to the boffin and died, in order to activate the ability the demon had to change their token to the banshee token. This made it difficult as someone knew to this ability to use it effectively

### Steps to reproduce

Setup game with Boffin, Imp and another minion.
Imp gets Banshee ability as Boffin is in play
Imp kill’s themselves and the other minion becomes the new Imp 
Old Imp HAS TO change their token to banshee in order to use the voting with two hands feature in the website

### Browser

Chrome

### Operating System

Windows

### Date and Time

September 30th 2024, 11:30

### Game Session

mondayblues

**Comment by bra1n** [comment]
Hi, 
we are aware of the fact, that running characters that gain another character's ability is currently a bit janky. This is in and of itself not a bug, but rather a current shortcoming of the app. We already have plans to add "secondary ability" to support as a new feature to the app eventually, but considering that this requires far-reaching changes, it is something that can't be done easily. So please be patient while we work on it. :-)
Keep an eye on #95 for any updates to this!
