### ISSUE TITLE
[BUG] Reminder tokens appear offset

### ISSUE THREAD

**Issue by zarst** [ThePandemoniumInstitute/botc-release#245]
### Description

While playing a game today I noticed (as well as another player that reminder tokens appeared to have the text offset to the left.

https://cdn.discordapp.com/attachments/1059764186621677698/1291915011857584280/image.png?ex=6701d51d&is=6700839d&hm=264fc789352cb9d9d83a2301d20ed1e8fbc2b4b5f065b46fe1ecbcac26f4f31d&

### Browser

Firefox

### Operating System

Windows

### Date and Time

OCtober 4 2024

### Game Session

https://botc.app/join/fridayfunday

### Relevant console log output

```shell
Browser Console Mode
Parent process only(Fast)
Multiprocess(Slower)
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF RemoteSettingsExperimentLoader.sys.mjs:709:21
Experiment tab-hover-preview-release-rollout has unknown featureId: tabPreview RemoteSettingsExperimentLoader.sys.mjs:709:21
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF RemoteSettingsExperimentLoader.sys.mjs:709:21
Experiment tab-hover-preview-release-rollout has unknown featureId: tabPreview RemoteSettingsExperimentLoader.sys.mjs:709:21
Warning: attempting to write 7720 bytes to preference browser.topsites.contile.cachedTiles. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
this.window.gBrowserInit is undefined ext-browser.js:1148:9
```

**Comment by pattersttv** [comment]
Thanks zarst, this seems to be a bug with the latest version of Firefox and we're looking into it.

**Comment by bra1n** [comment]
Hey there, if it is indeed happening on Firefox, then we'll have a fix ready for this with the next update!
