### ISSUE TITLE
[BUG] Dragging the "Text" box offscreen performs a Google search for "whispers"

### ISSUE THREAD

**Issue by NilesyBOTC** [ThePandemoniumInstitute/botc-release#246]
### Description

As in the title, if you drag the text box to the top of the screen, but accidentally go too high, it will perform a Google search for the term "whispers" and open in a new screen. 

### Steps to reproduce

Pop-out the Text tab.
Drag to the top of the screen in Chrome. 
Observe the new popped out tab for "whispers" 

### Browser

Chrome

### Operating System

Windows

### Date and Time

October 5th, 2024

### Game Session

Out of session 

### Relevant console log output

```shell
None relevant.
```

**Comment by bra1n** [comment]
This will be fixed with the next update. :-)
