### ISSUE TITLE
[BUG] using the same script and the same seat assignments will assign the same characters

### ISSUE THREAD

**Issue by kelseymayfield** [ThePandemoniumInstitute/botc-release#247]
### Description

When playing 2 games in a row, with the same script and the same seat positions (without gardener or shuffling seats), the same role will be assigned to the player in that seat if it is in play.

### Steps to reproduce

1. Have a group playing a game with a given script (e.g., Trouble Brewing).
2. Keep the same players in the same seats for a second game, without using the gardener fabled.
3. If any characters are in play from the previous game, the same player will be assigned that character (so if they were the imp in game 1, they will be the imp again).

### Browser

Chrome

### Operating System

Mac

### Date and Time

May 2024 to present (repeatable)

**Comment by pattersttv** [comment]
Hi Kelsey,

Is this something you're able to commonly repeat? If you could take a video, that'd be great.
I've just tried doing it a few times and couldn't get it to repeat the all of the same characters in the same place.

Thanks,
Patrick

**Comment by kelseymayfield** [comment]
Yes, it’s been a repeatable bug for a while - I will ask the ST to take a
screencap the next time I play. I do think it requires players to be seated
and it only happens when the same character is in play 2 games in a row -
which will always happen when it’s a one-demon script for example. I’ll let
you know when I can get that screencap!

**Comment by bra1n** [comment]
Do you happen to have a particular game session where this happened? If so, I'd need the session name and a rough timestamp for when it happened.

**Comment by bra1n** [comment]
Closed due lack of feedback / being unable to reproduce.
