### ISSUE TITLE
[BUG] Role Description Interaction 

### ISSUE THREAD

**Issue by Pooch13** [ThePandemoniumInstitute/botc-release#253]
### Description

When hovering over a player's role icon to see the description of their role and then pressing T to view player count, the is a weird interaction where the role description tile files over and gets very large. Specifically on tokens on the right side of the Grim where the text box shows up on the right side of the token.

### Steps to reproduce

1. Hover over role to view description. 
2. Press T to view player count.

### Browser

Chrome

### Operating System

Mac

### Date and Time

October 18th, 2pm PST

**Comment by bra1n** [comment]
Hey there, thanks for the report. This isn't exactly a new issue, but I'll make it a bit less glaring with the next update. :-)

**Comment by Pooch13** [comment]
Did I receive a "Bug" emote thingy from this?

**Comment by bra1n** [comment]
Not yet! You still need to send me your app user ID, since I don't know what your app account is to give you the emote.

**Comment by bra1n** [comment]
Done! :smile:
