### ISSUE TITLE
[BUG]  Voice indicator bars not showing in standalone app

### ISSUE THREAD

**Issue by SkunkAdamski** [ThePandemoniumInstitute/botc-release#254]
### Description

When playing in standalone app, voice indicator bras are not showing.

### Steps to reproduce

Go into standalone app, in a game with people speaking. Voice indicator bar doesn't show

### Browser

Standalone app

### Operating System

Windows

### Date and Time

October 20th, 9:45PM UK time

**Comment by bra1n** [comment]
Hi @SkunkAdamski, there has been a small bug with the voice indicator bars that was introduced with 3.34.0 for a couple of hours last Friday. I assume your app updated during that brief period of time. To fix it, can you please manually re-download and reinstall the app? You can find the download links here: https://github.com/ThePandemoniumInstitute/botc-release/releases/tag/v3.34.0
Afterwards, the problem should no longer occur. If it still does, please let us know in a comment here!
