### ISSUE TITLE
[BUG] Portrait Mode Mobile

### ISSUE THREAD

**Issue by sceneturkey** [ThePandemoniumInstitute/botc-release#256]
### Description

While in portrait mode on mobile, trying to select players on info cards doesn't work properly and the selection areas are around 3-4 token lengths away from the actual tokens.

### Steps to reproduce

1. Open app on mobile
2. Play in Portrait mode
3. Enter night phase
4. Send info card
5. Select players

### Browser

Firefox

### Operating System

Android

### Date and Time

Oct 22nd, 2024 4:42am CST

**Comment by bra1n** [comment]
Thanks, this will be fixed with the next update!
