### ISSUE TITLE
[FEATURE] Re-Enable viewing your own camera during night phase

### ISSUE THREAD

**Issue by genestealer** [ThePandemoniumInstitute/botc-release#257]
### What problem are you trying to solve?

You can no longer view your own camera during the night phase.
Issue: You cannot "monitor" what you may accidentally be sending to the storyteller who can see the video during the night phase.
I.E. Leaking nudes..... / Getting changed / forget you are on camera.

### Describe the solution you'd like

Re-enable option to view your own camera during the night phase

### Alternatives you have considered

N/A

**Comment by genestealer** [comment]
Update: Sorry, did not know that the ST cannot see the video feeds during the night, my error.

Option to see video at night would still be nice.

**Comment by bra1n** [comment]
This is already an option, but for the ST only. If you want to play with cams at night (but only visible to yourself and the ST), then ask the ST to enable this setting:
![image](https://github.com/user-attachments/assets/544c557c-595c-4d79-9b88-b2b53866528b)
