### ISSUE TITLE
[FEATURE] Direction night signals for Shugenja

### ISSUE THREAD

**Issue by Alek2ander** [ThePandemoniumInstitute/botc-release#258]
### What problem are you trying to solve?

There's no convenient way to send information to a Shugenja using the night signal tool - it needs to use custom text signals or be shown as pointing to a player (which isn't immediately obvious and might imply for newer players more than the information actually means). In a physical game, it's trivial to gesture "👈 this way".

### Describe the solution you'd like

Add "🔄 counter-clockwise" and "🔃 clockwise" as built-in hand signals for the storyteller.

**Comment by bra1n** [comment]
Makes sense, this will be added with the next update!
