### ISSUE TITLE
[FEATURE] Add British English localisation (Sorry I mean "localization") translation

### ISSUE THREAD

**Issue by genestealer** [ThePandemoniumInstitute/botc-release#260]
### What problem are you trying to solve?

British English / UK English localisation

### Describe the solution you'd like

Can we please have a British English / UK English localisation added to the app, to deal with the spelling differences?

**Comment by bra1n** [comment]
Hey there, once translation support is in the app, we're going to set up a procedure for our users to submit fan-made translations, including specific dialects. At that point you'll be able to create an EN_GB translation if you would like to. :-)
