### ISSUE TITLE
[BUG] Json saving

### ISSUE THREAD

**Issue by morime-please** [ThePandemoniumInstitute/botc-release#262]
### Description

I was unable to save the JSON when looking at the script as the title of the script and text of a character not allowing me to save the JSON. 

### Steps to reproduce

move the json to the bottom again and have pop up next to allow both to be interacted with.

### Browser

Chrome

### Operating System

Windows

### Date and Time

Nov 1st, 10pm BST

### Game Session

https://botc.app/join/the%20best%20lobby

**Comment by bra1n** [comment]
Hey there, thanks for the report, this has indeed been a recently introduced bug, which will be fixed with the next update!
