### ISSUE TITLE
[FEATURE] increase Character Name length limit for Translated characters

### ISSUE THREAD

**Issue by AdmiralGT** [ThePandemoniumInstitute/botc-release#263]
### Description

The script schema has been updated to set a maximum character name length of 20 characters. However, many translated character names per the unofficial translations are longer than this.

```
Encantador de serpientes
es_ES - snakecharmer
Bibliotecario infernal
es_ES - hellslibrarian
Prêcheur de l'Apocalypse
fr_FR - doomsayer
Cultivateur de pavot
fr_FR - poppygrower
Bibliothécaire de l'enfer
fr_FR - hellslibrarian
Incantatore di Serpenti
it_IT - snakecharmer
Avvocato del Diavolo
it_IT - devilsadvocate
Cacciatore di Taglie
it_IT - bountyhunter
Cacciatore di Taglie
it_IT - huntsman
Collezionista d'Ossa
it_IT - bonecollector
Coltivatore di Papaveri
it_IT - poppygrower
Bibliotecario Infernale
it_IT - hellslibrarian
Encantador de Serpentes
pt_BR - snakecharmer
Caçador de Recompensas
pt_BR - bountyhunter
Bibliotecário do Inferno
pt_BR - hellslibrarian
Encantador de Serpentes
pt_PT - snakecharmer
Caçador de Recompensas
pt_PT - bountyhunter
Bibliotecário do Inferno
pt_PT - hellslibrarian
Scharlakansröd Kvinna
sv_SE - scarletwoman
Helvetets Biblotikarie
sv_SE - hellslibrarian
```

30 characters is probably an appropriate length.

### Browser

Other (specify in comments)

### Operating System

Windows

### Date and Time

Irrelevant

**Comment by bra1n** [comment]
Hey, this is not really a "bug", but more like a feature request. I agree that it makes sense, especially once translations are available officially, to increase the length. However, there would first need to be support for rendering longer character names on player tokens, before I could increase the schema limit to 30. I'll look into it!

**Comment by bra1n** [comment]
Alright, the max character name length will be increased to 30 with the next update, as will the max reminder token length. See: https://github.com/ThePandemoniumInstitute/botc-release/commit/1c9be19dabde5b6b5b63a3c6609747b921acd18e
