### ISSUE TITLE
[BUG] If app tutorial steps are disabled you cannot hand out characters when a gardener is in play

### ISSUE THREAD

**Issue by ACrispyDuck** [ThePandemoniumInstitute/botc-release#274]
### Description

When the app tutorial steps are disabled and a gardener is in play, there is no way to hand out character tokens.

### Browser

Firefox

### Operating System

Windows

### Date and Time

27/11/24

**Comment by bra1n** [comment]
Hey, have you tried clicking on the Gardener Fabled token? :smile:

**Comment by ACrispyDuck** [comment]
Missed that option
