### ISSUE TITLE
[FEATURE] Translate the app to other languages (Spanish)

### ISSUE THREAD

**Issue by elessargng** [ThePandemoniumInstitute/botc-release#278]
### What problem are you trying to solve?

Try to make the application access to people who does not understand English. 

### Describe the solution you'd like

I don't know if the app supports different languages, but the ideal solution would be to have all the literals in a properties file ready to be translated.

### Comments

I could translate the game to Spanish.

**Comment by bra1n** [comment]
Hi,
there are plans to add official translations (including Spanish) to the app soon! :-)
