### ISSUE TITLE
Track ghost votes

### ISSUE THREAD

**Issue by bra1n** [ThePandemoniumInstitute/botc-release#34]
I would like the app to note when a ghost vote has been used and automatically remove it  - it would be one less thing for the ST to have to do.

**Comment by Tomgxz** [comment]
This would need to be toggleable for votes such as cult leader and exiles.

**Comment by bra1n** [comment]
Exile votes are already handled differently and Cult Leader shouldn't be an actual vote but just everyone who wants to join the cult should raise their hand.
