### ISSUE TITLE
Camera is not working during a game 

### ISSUE THREAD

**Issue by BambiYoda** [ThePandemoniumInstitute/botc-release#78]
-Since, just several days, I have a technical issues  about the new app, I'm no longer on Patreon so I don't know 🤷🏻‍♀️ who to contact
  On the settings everything works, I see my camera 🎥 but the camera does not work when it's the game.
  I use chrome just for this application because I'm on MacBook 💻 pro 2021, everything works fine until Thursday 
  I tried with Safari but this app does not working very well on safari, we don’t see all outputs for the camera.
 I think maybe a new upload about this app breaking something 
  Thank You for our help 
  🙂

**Comment by bra1n** [comment]
Hi Bambi,

thanks for the report! Chrome changed something about their browser video codecs with a recent update, which broke the cams on the app, unfortunately. I've already developed a bugfix for this and it will be released with the update later this week. :-)
