### ISSUE TITLE
Issues with Webcams

### ISSUE THREAD

**Issue by Woogz-git** [ThePandemoniumInstitute/botc-release#79]
For the last two weeks a portion of our players are really struggling to get their webcams to show. The light on some of their webcams is on. They can see themselves when they go to set up their camera they can see themselves but then when they click on "back" it doesn't show.

They can see the toggle camera icon and clicking it toggles the icon but doesn't actually do anything. Here's our session info. Mine is working fine and so is 3 of our other players but 3 of them it's not working for.

BOTC Online v3.7.1  ID: 6301373726874 Subscription: app-boosted Expires on: 3/15/2023

The 3 guys not working are all on PC and all using Chrome or Brave.

The people having an issue switched to Firefox and it fixed it so there's some weird issue with Chrome. 2 of the 3 are on Win 11 but the 3rd is on Win 10 so don't know that's the issue.

The 3 people who switched to firefox are all working now but their webcams are 5 seconds delayed from their audio. All 3 of them.

**Comment by bra1n** [comment]
Hey @Woogz-git, thanks for your bug report! This is a known issue and as I said in #78, it will be fixed with the update tomorrow. :-) Sorry for the inconvenience!
