### ISSUE TITLE
Streaming ST Sequester Mode

### ISSUE THREAD

**Issue by CTNafe** [ThePandemoniumInstitute/botc-release#80]
The app currently does not allow the Storyteller to affect the game state like choosing roles or finalizing night actions from a room. From a streaming perspective, this makes it difficult to communicate why I'm doing things since it would be the storyteller talking over the conversations of the players at night. This would also be helpful when guiding a Co-ST. 

I would request the ability for the storyteller to affect the game state in at least one chat room, especially when selecting characters for the bag.

**Comment by bra1n** [comment]
That's a great idea, one that I've seen Ben and other streamers struggle with as well. I'll add a way to "minimize" the current room without actually leaving it, so that you can modify the game state easier.

**Comment by bra1n** [comment]
So, you can already select roles or finalize night actions when in a private chat, but I'm adding some code that will allow you to reposition the minized chat windows, in order to give you easier access to the full app while chatting.

**Comment by CTNafe** [comment]
That's a great idea, Steffen! Thanks for implementing that.

**Comment by bra1n** [comment]
The minimized chat popup can be repositioned now.
