### ISSUE TITLE
First night reminder for minion info not clear for online ST

### ISSUE THREAD

**Issue by jntrnr** [ThePandemoniumInstitute/botc-release#84]
**Describe the bug**

The first night guidance for minion info is "wake all minions, show the THIS IS THE DEMON token". In person, the minions would wake together and see each other. Online, however, this requires an extra step the ST needs to do to allow the minions to learn what other players are minions. The app is set up to wake one player at a time, so if you follow the text online as it is today, you'd wake each minion in turn and show them who the demon is, but you wouldn't show them who the fellow minions are (as the text doesn't remind you to do so).

Perhaps the text could be changed to better remind online ST's to share not only which player is the demon but which players are fellow minions, so that they don't miss that step of the first night?

**To Reproduce**
1. Go to First Night
2. Read the guidance for the Minion's info for the first night
3. Possibly misread the guidance

**Expected behavior**

**Browser app (please complete the following information):**
- (Not Browser specific)
- 3.11.0

**Standalone app (please complete the following information):**
- (Not OS specific)
- 3.11.0

**Comment by graycarper** [comment]
This would be good quality of life improvement to keep us storytellers on track!

**Comment by bra1n** [comment]
Good point, I'll add this info to the Minion reminder on the night order sheets!

**Comment by graycarper** [comment]
Wonderful! Thank you!

**Comment by bra1n** [comment]
Done
