### ISSUE TITLE
none of the night order stuff working 

### ISSUE THREAD

**Issue by Guldath** [ThePandemoniumInstitute/botc-release#86]
I ran a teensy for some friends on 6/15. I couldn't get any of the night actions to work at all during the game other than being able to mark someone for death then revealing it at dawn. None of the cards worked and i'm not sure why.

**Comment by bra1n** [comment]
Hey @Guldath, what exactly happened when you tried to use the cards? Also, do you have a game session name for me so that I can take a look at the logs?

**Comment by Guldath** [comment]
It would not bring up the cards at all. I tried it again the next day and it seems to be working now, not sure what happened. The session name was  Leon.

**Comment by bra1n** [comment]
Weird. If it happens again, please take a look [at the browser console](https://screenful.com/how-to-open-the-browser-console) and see if there's any error messages. That would be very helpful when tracking down the cause of the problem. :-)
