### ISSUE TITLE
t is null error

### ISSUE THREAD

**Issue by Guldath** [ThePandemoniumInstitute/botc-release#87]
When i try to log on to the ST role I get an error that t is null. I have tried multiple times and get the same result every time.

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/100069148/e67eddf2-8ba9-40d2-9000-bf8c2fe407d3)

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/100069148/cb2aef53-c971-40bc-b7f3-dd53c5d0afd8)

I am currently using Firefox for my browser

**Comment by bra1n** [comment]
Hi Guldath, I've just released v3.12.1, which should hopefully fix this issue. If not, could you please try using the incognito mode on the app and create a game session then?

**Comment by Guldath** [comment]
Used Private browser and now it's working, Thanks for all your help!
