### ISSUE TITLE
Push To Talk getting Cut off.

### ISSUE THREAD

**Issue by QuindoHL** [ThePandemoniumInstitute/botc-release#88]
**Describe the bug**
The timing of push to talk is cutting off an entire word.

**To Reproduce**
Use push to talk and release the button as soon as you finish the last word

**Expected behavior**
The entire sentence should be hearable.

**Browser app (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114.0.5735.134 

It would be nice if there was a MS offset that can be set that delays the muting of the mic.

**Comment by bra1n** [comment]
I think it makes sense to add a flat 500ms delay to the end of a push to talk voice activation, so I'm going to do that for the next update.

**Comment by bra1n** [comment]
Will be added with 3.12.2
