### ISSUE TITLE
About To Die skull remains on player killed when Grim was revealed.

### ISSUE THREAD

**Issue by botcscriptcheck** [ThePandemoniumInstitute/botc-release#90]
**Describe the bug**
When a player is executed and then the Grim is revealed, the "About to die" skull remains on that player.

**To Reproduce**
1. Run a vote, marking someone as executed at the end
2. Put a shroud on that player, making them dead.
3. Begin to reveal the grimoire
4. The Grim will still have the skull above the player who was just killed.

**Expected behavior**
The skull shouldn't be there

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/135992257/a6a9265f-c85e-40d5-ab0b-d2147b2ebf53)

**Standalone app (please complete the following information):**
 - OS: Windows 11
 - Version 3.12.1

**Additional context**
- Game session name: #kiwis
- Date and time when it happened: June 24th 2023, approx 10:40pm NZST

**Comment by bra1n** [comment]
Thanks for the report! I've also encountered this bug and will fix it soon. :-)
