### ISSUE TITLE
Echo while using app

### ISSUE THREAD

**Issue by matas-ramanauskas-revel** [ThePandemoniumInstitute/botc-release#92]
**Describe the bug**
There is echo while using app (No echo when using browser)

**To Reproduce**
1. Open app.
2. Join game

**Comment by bra1n** [comment]
Thanks for the bug report, this might've been caused by the recent changes to the audio chat. I'm rolling some of them back with the upcoming update, so hopefully this will no longer be an issue with v3.12.2
