### ISSUE TITLE
No user video in browser

### ISSUE THREAD

**Issue by matas-ramanauskas-revel** [ThePandemoniumInstitute/botc-release#93]
Cannot see other peoples video after version update (3.12.1) in browser. Others can see me, I selected show settings. But still cannot see.

**Comment by bra1n** [comment]
Maybe you have "Show Camera Feeds" disabled in the settings? Or you're in the night phase?

**Comment by matas-ramanauskas-revel** [comment]
It worked on some browsers, but not on all. On Brave it did not work (it worked previously)

**Comment by bra1n** [comment]
Hi, I've released 3.12.2 end of last week, maybe that has fixed your issues? Did you try again since the update?
