### ISSUE TITLE
Dual channel audio input is not downmixed for voice chat

### ISSUE THREAD

**Issue by LShirohana** [ThePandemoniumInstitute/botc-release#96]
**Describe the bug**
When you use an XLR mic with an audio interface with two inputs, usually this is the left and right channel respectively. This is often an issue though, depending on what you are doing/what game you are playing. Specifically, if you are using only a microphone input into 1 port, it will often only appear from the left channel (or right, if you do the other input)

This is a bug in how most people treat audio, though. Discord, and other VOIP programs will downmix dual channel audio into mono specifically for this reason, so that players dont say "Why are you coming out of only my left ear?"

**To Reproduce**
1. Have Audio interface with dual channel audio input, and use it
2. Play BOTC with said audio
3. Said friends will point out you only appear from 1 channel

**Expected behavior**
I expect my audio to be mono, or, alternatively, copied over to the other, empty channel. (Although, I am not sure which option is better. Would copying the channel to the other double the volume? Not sure.

Personally, I think having a checkbox/setting that allows us to downmix into mono would fix this issue for users like me who have XLR mics with audio interfaces, while still allowing for the fancy streamers **who do** use multiple inputs, to keep doing what they are doing

**Browser app (please complete the following information):**
 - OS: Windows 10 Version 10.0.19045 Build 19045
 - Browser: Firefox 115.0.2 (64-bit)
 - Version: v3.13.0

**Comment by bra1n** [comment]
Hi Mitch,

thanks for the bug report! I'll try to fix this with the upcoming update by downsampling all audio inputs to mono. This should not only prevent odd audio channel bugs like yours but also increase bandwidth usage.

**Comment by bra1n** [comment]
Update is live now.

**Comment by LShirohana** [comment]
Can confirm the fix worked for my issue in particular. Thanks!

**Comment by bra1n** [comment]
Awesome, thank you for the feedback!
