### ISSUE TITLE
Screen Glitch

### ISSUE THREAD

**Issue by TechnicallyAFK** [ThePandemoniumInstitute/botc-release#97]
**Describe the bug**
At one point (after the game had finished) my screen suddenly looked like this (screenshot), left half of my screen showing part of my grimoire, and the right half of the screen showing the character sheet. 

**To Reproduce**
I've got no idea how I caused this to happen, I think it was the result of random keyboard inputs & mouse clicks. Been trying to recreate this with no luck. 

**Expected behavior**
I did not expect this to happen, I believe I was testing hotkeys or something. 

**Screenshots**
![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/66129929/a94e91f6-9b9b-4699-8abc-c4f5b5c993d5)

**Browser app (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 3.14.0 (clocktower app version right?)

**Additional context**
- July 30th @ 1PM PST
- Refreshing my page fixed the issue, just thought I might bring it up anyways.

**Comment by bra1n** [comment]
Hey @TechnicallyAFK, thanks for the bug report! This will be fixed in the upcoming update. :-)
FYI, the key you pressed that caused the glitch was TAB, but only on custom scripts.
