### ISSUE TITLE
Make the Pixie's "Has Ability" reminder token set the correct night order for the Pixie

### ISSUE THREAD

**Issue by botcscriptcheck** [ThePandemoniumInstitute/botc-release#98]
**Describe the solution you'd like**
When the Pixie's "Has Ability" reminder token is placed on any player, set the Pixie's "Other Night" order number to the same number as the player they were mad about.

**Describe alternatives you've considered**
Just remembering is fine, but it's kinda messy to keep remembering every time.

**Additional context**
I remembered this could be an option after seeing the Cannibal's "Died Today" reminder token sets the correct night order location, which is very helpful.

**Comment by bra1n** [comment]
Hey @botcscriptcheck,
good idea, and since it's so similar to the Cannibal ability in the regard of the Night Order, I'll add it with the next update! :-)

**Comment by bra1n** [comment]
Done
