### ISSUE TITLE
Add shortcut keys for "Good Wins", "Evil Wins", "Game Result" and "Remaining Players"

### ISSUE THREAD

**Issue by GarethOates** [ThePandemoniumInstitute/botc-release#99]
**Is your feature request related to a problem? Please describe.**
I like to use my Elgato StreamDeck to control the application.  Currently I can press "G" to Reveal the Grimoire but there is no keyboard shortcut for the "Good Wins" or "Evil Wins" buttons.  This would be nice to have.

**Describe the solution you'd like**
It would be good to be able to assign shortcut keys to the "Good Wins" or "Evil Wins" buttons that are visible after the Grimoire is revealed.  Maybe "A" for Good Wins and "E" for Evil Wins.

**Describe alternatives you've considered**
Currently the only way to do this is by clicking the mouse or using the tab key and then space.  This is great for accessibility, but not so much for stream decks. :) 

**Additional context**
It would also be good to have some additional shortcuts for the "Game Result" and "Remaining Players" buttons too.

**Comment by bra1n** [comment]
Good idea, it would make sense to have some general shortcuts for dialogue popups anyway, like using [1], [2], [3], etc. for the buttons there. I'll see what I can do!

**Comment by bra1n** [comment]
This has been added with v3.17.0

**Comment by GarethOates** [comment]
Thanks @bra1n I used it the other day and it worked great. The 1,2,3 keys didn't work on the final box for "Game Result" or "Remaining Players" buttons though.  Maybe this was just an oversight?

**Comment by bra1n** [comment]
Ah yeah, that's not a dialogue popup, but an "overlay". It's a bit more tricky to add shortcuts there, since it's not self-contained but part of the normal app and might interfere with other shortcuts.
